// Generated from the native menu-bar capture of PowerPoint for Mac 16.113.3
// (AX read of every menu in the English and Japanese UI, 2026-10-07). Do not
// edit by hand: order, separators ('-'), labels and shortcut glyphs are
// PowerPoint's. 🌐 marks the fn/Globe modifier (AX modifier bit 4).
//
// Left out: the application menu ("PowerPoint": About, Settings, Services,
// Hide, Quit), which belongs to the browser here, and lists that name things
// on the capture machine (Open Recent's documents, the subtitle languages and
// microphones). Japanese items carry the id of their English counterpart, so
// commands bind once; PowerPoint orders the Japanese Window and Slide Show
// menus differently and has no Rehearse with Coach in Japanese.
//
// The one deliberate departure: items whose label names the product (its
// Add-ins and Help items) carry neutral labels and ids, because the editor
// must not show a third-party trademark as its own UI.

export interface NativeMenuItem {
  readonly id: string;
  readonly label: string;
  readonly shortcut?: string;
  readonly children?: readonly NativeMenuEntry[];
}
export type NativeMenuEntry = NativeMenuItem | '-';
export interface NativeMenu {
  readonly id: string;
  readonly label: string;
  readonly items: readonly NativeMenuEntry[];
}

/** Format ▸ Apply Object Style's name while nothing is selected. */
export const APPLY_TO_DEFAULTS = {
  en: 'Apply To Defaults',
  ja: '標準に適用',
} as const;

export const NATIVE_MENUBAR: {
  readonly en: readonly NativeMenu[];
  readonly ja: readonly NativeMenu[];
} = {
  en: [
    {
      id: 'file',
      label: 'File',
      items: [
        { id: 'file/new-presentation', label: 'New Presentation', shortcut: '⌘N' },
        { id: 'file/new-from-template', label: 'New from Template...', shortcut: '⇧⌘P' },
        { id: 'file/open', label: 'Open...', shortcut: '⌘O' },
        {
          id: 'file/open-recent',
          label: 'Open Recent',
          children: [{ id: 'file/open-recent/more', label: 'More...', shortcut: '⇧⌘O' }],
        },
        '-',
        { id: 'file/close', label: 'Close', shortcut: '⌘W' },
        { id: 'file/save', label: 'Save', shortcut: '⌘S' },
        { id: 'file/save-as', label: 'Save As...', shortcut: '⇧⌘S' },
        { id: 'file/save-as-template', label: 'Save as Template...' },
        { id: 'file/export', label: 'Export...' },
        { id: 'file/move', label: 'Move...' },
        { id: 'file/rename', label: 'Rename...' },
        '-',
        { id: 'file/browse-version-history', label: 'Browse Version History' },
        '-',
        {
          id: 'file/share',
          label: 'Share',
          children: [
            { id: 'file/share/share', label: 'Share...' },
            '-',
            { id: 'file/share/send-presentation', label: 'Send Presentation' },
            { id: 'file/share/send-pdf', label: 'Send PDF' },
          ],
        },
        '-',
        { id: 'file/always-open-read-only', label: 'Always Open Read-Only' },
        { id: 'file/restrict-permissions', label: 'Restrict Permissions', children: [] },
        { id: 'file/passwords', label: 'Passwords...' },
        '-',
        { id: 'file/compress-pictures', label: 'Compress Pictures...' },
        '-',
        { id: 'file/page-setup', label: 'Page Setup...' },
        { id: 'file/print', label: 'Print...', shortcut: '⌘P' },
        '-',
        { id: 'file/properties', label: 'Properties' },
      ],
    },
    {
      id: 'edit',
      label: 'Edit',
      items: [
        { id: 'edit/undo', label: 'Undo Paragraph Style', shortcut: '⌘Z' },
        { id: 'edit/repeat', label: 'Repeat Preview', shortcut: '⌘Y' },
        '-',
        { id: 'edit/cut', label: 'Cut', shortcut: '⌘X' },
        { id: 'edit/copy', label: 'Copy', shortcut: '⌘C' },
        '-',
        { id: 'edit/paste', label: 'Paste', shortcut: '⌘V' },
        { id: 'edit/paste-special', label: 'Paste Special...', shortcut: '⌃⌘V' },
        {
          id: 'edit/paste-and-match-formatting',
          label: 'Paste and Match Formatting',
          shortcut: '⌥⇧⌘V',
        },
        '-',
        { id: 'edit/clear', label: 'Clear' },
        { id: 'edit/select-all', label: 'Select All', shortcut: '⌘A' },
        { id: 'edit/duplicate', label: 'Duplicate', shortcut: '⌘D' },
        { id: 'edit/delete-slide', label: 'Delete Slide' },
        '-',
        { id: 'edit/remove-section', label: 'Remove Section' },
        { id: 'edit/rename-section', label: 'Rename Section' },
        '-',
        {
          id: 'edit/find',
          label: 'Find',
          children: [
            { id: 'edit/find/find', label: 'Find...', shortcut: '⌘F' },
            { id: 'edit/find/find-next', label: 'Find Next', shortcut: '⌘G' },
            { id: 'edit/find/find-previous', label: 'Find Previous', shortcut: '⇧⌘G' },
            { id: 'edit/find/advanced-find', label: 'Advanced Find...', shortcut: '⌃F' },
            '-',
            { id: 'edit/find/replace', label: 'Replace...', shortcut: '⌃H' },
            { id: 'edit/find/replace-fonts', label: 'Replace Fonts...' },
          ],
        },
        { id: 'edit/select-data', label: 'Select Data...' },
        '-',
        { id: 'edit/toggle-drawing', label: 'Toggle Drawing', shortcut: '⌃⌘Z' },
        '-',
        {
          id: 'edit/autofill',
          label: 'AutoFill',
          children: [
            { id: 'edit/autofill/contact', label: 'Contact…' },
            { id: 'edit/autofill/passwords', label: 'Passwords…' },
            { id: 'edit/autofill/credit-card', label: 'Credit Card…' },
          ],
        },
        { id: 'edit/start-dictation', label: 'Start Dictation', shortcut: '🎤' },
        { id: 'edit/emoji-and-symbols', label: 'Emoji & Symbols', shortcut: '🌐' },
      ],
    },
    {
      id: 'view',
      label: 'View',
      items: [
        { id: 'view/normal', label: 'Normal', shortcut: '⌘1' },
        { id: 'view/slide-sorter', label: 'Slide Sorter', shortcut: '⌘2' },
        { id: 'view/notes-page', label: 'Notes Page', shortcut: '⌘3' },
        { id: 'view/outline-view', label: 'Outline View', shortcut: '⌘4' },
        { id: 'view/reading-view', label: 'Reading View', shortcut: '⌘5' },
        { id: 'view/presenter-view', label: 'Presenter View', shortcut: '⌥↩' },
        { id: 'view/slide-show', label: 'Slide Show', shortcut: '⇧⌘↩' },
        '-',
        { id: 'view/show-slides', label: 'Show Slides', shortcut: '⌃⇧⇥' },
        '-',
        {
          id: 'view/master',
          label: 'Master',
          children: [
            { id: 'view/master/slide-master', label: 'Slide Master', shortcut: '⌥⌘1' },
            { id: 'view/master/handout-master', label: 'Handout Master', shortcut: '⌥⌘2' },
            { id: 'view/master/notes-master', label: 'Notes Master', shortcut: '⌥⌘3' },
          ],
        },
        '-',
        { id: 'view/ribbon', label: 'Ribbon', shortcut: '⌥⌘R' },
        { id: 'view/message-bar', label: 'Message Bar' },
        '-',
        { id: 'view/header-and-footer', label: 'Header and Footer...' },
        { id: 'view/markup', label: 'Markup' },
        { id: 'view/advanced-markup', label: 'Advanced Markup' },
        '-',
        { id: 'view/ruler', label: 'Ruler' },
        {
          id: 'view/grid-and-guides',
          label: 'Grid and Guides',
          children: [
            { id: 'view/grid-and-guides/smart-guides', label: 'Smart Guides' },
            { id: 'view/grid-and-guides/guides', label: 'Guides', shortcut: '⌃⌥⌘G' },
            { id: 'view/grid-and-guides/gridlines', label: 'Gridlines', shortcut: '⌘^' },
            '-',
            { id: 'view/grid-and-guides/snap-to-grid', label: 'Snap to Grid' },
            '-',
            { id: 'view/grid-and-guides/grid-options', label: 'Grid Options...' },
          ],
        },
        {
          id: 'view/zoom',
          label: 'Zoom',
          children: [
            { id: 'view/zoom/fit-to-window', label: 'Fit to Window', shortcut: '⌥⌘O' },
            { id: 'view/zoom/zoom-in', label: 'Zoom In', shortcut: '⌘+' },
            { id: 'view/zoom/zoom-out', label: 'Zoom Out', shortcut: '⌘-' },
            '-',
            { id: 'view/zoom/zoom', label: 'Zoom...' },
          ],
        },
        { id: 'view/enter-full-screen', label: 'Enter Full Screen', shortcut: '🌐F' },
      ],
    },
    {
      id: 'insert',
      label: 'Insert',
      items: [
        { id: 'insert/new-slide', label: 'New Slide', shortcut: '⇧⌘N' },
        { id: 'insert/duplicate-slide', label: 'Duplicate Slide', shortcut: '⇧⌘D' },
        {
          id: 'insert/slides-from',
          label: 'Slides From',
          children: [
            { id: 'insert/slides-from/reuse-slides', label: 'Reuse Slides...' },
            { id: 'insert/slides-from/outline', label: 'Outline...' },
          ],
        },
        '-',
        { id: 'insert/section', label: 'Section' },
        { id: 'insert/comment', label: 'Comment', shortcut: '⇧⌘M' },
        '-',
        { id: 'insert/wordart', label: 'WordArt' },
        { id: 'insert/header-and-footer', label: 'Header and Footer...' },
        { id: 'insert/date-and-time', label: 'Date and Time...' },
        { id: 'insert/slide-number', label: 'Slide Number' },
        '-',
        { id: 'insert/table', label: 'Table...' },
        {
          id: 'insert/chart',
          label: 'Chart',
          children: [
            { id: 'insert/chart/column', label: 'Column' },
            { id: 'insert/chart/bar', label: 'Bar' },
            { id: 'insert/chart/line', label: 'Line' },
            { id: 'insert/chart/area', label: 'Area' },
            { id: 'insert/chart/pie', label: 'Pie' },
            { id: 'insert/chart/treemap', label: 'Treemap' },
            { id: 'insert/chart/sunburst', label: 'Sunburst' },
            { id: 'insert/chart/histogram', label: 'Histogram' },
            { id: 'insert/chart/pareto', label: 'Pareto' },
            { id: 'insert/chart/box-and-whisker', label: 'Box and Whisker' },
            { id: 'insert/chart/x-y-scatter', label: 'X Y (Scatter)' },
            { id: 'insert/chart/waterfall', label: 'Waterfall' },
            { id: 'insert/chart/funnel', label: 'Funnel' },
            { id: 'insert/chart/stock', label: 'Stock' },
            { id: 'insert/chart/surface', label: 'Surface' },
            { id: 'insert/chart/radar', label: 'Radar' },
            { id: 'insert/chart/filled-map', label: 'Filled Map' },
          ],
        },
        {
          id: 'insert/smartart',
          label: 'SmartArt',
          children: [
            { id: 'insert/smartart/list', label: 'List' },
            { id: 'insert/smartart/process', label: 'Process' },
            { id: 'insert/smartart/cycle', label: 'Cycle' },
            { id: 'insert/smartart/hierarchy', label: 'Hierarchy' },
            { id: 'insert/smartart/relationship', label: 'Relationship' },
            { id: 'insert/smartart/matrix', label: 'Matrix' },
            { id: 'insert/smartart/pyramid', label: 'Pyramid' },
            { id: 'insert/smartart/picture', label: 'Picture' },
            { id: 'insert/smartart/timeline', label: 'Timeline' },
            { id: 'insert/smartart/meet-the-team', label: 'Meet The Team' },
            { id: 'insert/smartart/text-card', label: 'Text Card' },
          ],
        },
        '-',
        {
          id: 'insert/picture',
          label: 'Picture',
          children: [
            { id: 'insert/picture/photo-browser', label: 'Photo Browser…' },
            { id: 'insert/picture/picture-from-file', label: 'Picture from File...' },
            { id: 'insert/picture/stock-images', label: 'Stock Images...' },
            { id: 'insert/picture/online-pictures', label: 'Online Pictures...' },
            { id: 'insert/picture/brand-images', label: 'Brand Images...' },
          ],
        },
        {
          id: 'insert/audio',
          label: 'Audio',
          children: [
            { id: 'insert/audio/audio-browser', label: 'Audio Browser...' },
            { id: 'insert/audio/audio-from-file', label: 'Audio from File...' },
            '-',
            { id: 'insert/audio/record-audio', label: 'Record Audio...' },
          ],
        },
        {
          id: 'insert/video',
          label: 'Video',
          children: [
            { id: 'insert/video/movie-browser', label: 'Movie Browser...' },
            { id: 'insert/video/movie-from-file', label: 'Movie from File...' },
            { id: 'insert/video/stock-videos', label: 'Stock Videos...' },
            { id: 'insert/video/online-movie', label: 'Online Movie...' },
          ],
        },
        { id: 'insert/cameo', label: 'Cameo' },
        { id: 'insert/equation', label: 'Equation' },
        { id: 'insert/symbol', label: 'Symbol...' },
        {
          id: 'insert/shape',
          label: 'Shape',
          children: [
            { id: 'insert/shape/rectangle', label: 'Rectangle' },
            { id: 'insert/shape/rounded-rectangle', label: 'Rounded Rectangle' },
            { id: 'insert/shape/triangle', label: 'Triangle' },
            { id: 'insert/shape/oval', label: 'Oval' },
            { id: 'insert/shape/line', label: 'Line' },
          ],
        },
        '-',
        { id: 'insert/icons', label: 'Icons...' },
        '-',
        {
          id: 'insert/3d-models',
          label: '3D Models',
          children: [
            { id: 'insert/3d-models/insert-3d-model-from', label: 'Insert 3D Model From' },
            { id: 'insert/3d-models/stock-3d-models', label: 'Stock 3D Models...' },
            { id: 'insert/3d-models/this-device', label: 'This Device...' },
          ],
        },
        '-',
        {
          id: 'insert/zoom',
          label: 'Zoom',
          children: [
            { id: 'insert/zoom/summary-zoom', label: 'Summary Zoom' },
            { id: 'insert/zoom/section-zoom', label: 'Section Zoom' },
            { id: 'insert/zoom/slide-zoom', label: 'Slide Zoom' },
          ],
        },
        '-',
        {
          id: 'insert/action-buttons',
          label: 'Action Buttons',
          children: [
            { id: 'insert/action-buttons/action-buttons', label: 'Action Buttons' },
            { id: 'insert/action-buttons/back-or-previous', label: 'Back or Previous' },
            { id: 'insert/action-buttons/forward-or-next', label: 'Forward or Next' },
            { id: 'insert/action-buttons/beginning', label: 'Beginning' },
            { id: 'insert/action-buttons/end', label: 'End' },
            { id: 'insert/action-buttons/home', label: 'Home' },
            { id: 'insert/action-buttons/information', label: 'Information' },
            { id: 'insert/action-buttons/return', label: 'Return' },
            { id: 'insert/action-buttons/movie', label: 'Movie' },
            { id: 'insert/action-buttons/document', label: 'Document' },
            { id: 'insert/action-buttons/sound', label: 'Sound' },
            { id: 'insert/action-buttons/help', label: 'Help' },
            { id: 'insert/action-buttons/custom', label: 'Custom' },
          ],
        },
        { id: 'insert/action-settings', label: 'Action Settings...' },
        '-',
        { id: 'insert/object', label: 'Object...' },
        { id: 'insert/hyperlink', label: 'Hyperlink...', shortcut: '⌘K' },
      ],
    },
    {
      id: 'format',
      label: 'Format',
      items: [
        { id: 'format/font', label: 'Font...', shortcut: '⌘T' },
        { id: 'format/paragraph', label: 'Paragraph...', shortcut: '⌥⌘M' },
        '-',
        { id: 'format/bullets-and-numbering', label: 'Bullets and Numbering...' },
        '-',
        { id: 'format/columns', label: 'Columns...' },
        {
          id: 'format/alignment',
          label: 'Alignment',
          children: [
            { id: 'format/alignment/align-left', label: 'Align Left', shortcut: '⌘L' },
            { id: 'format/alignment/center', label: 'Center', shortcut: '⌘E' },
            { id: 'format/alignment/align-right', label: 'Align Right', shortcut: '⌘R' },
            { id: 'format/alignment/justify', label: 'Justify' },
            { id: 'format/alignment/distributed', label: 'Distributed' },
          ],
        },
        { id: 'format/more-options', label: 'More Options...' },
        '-',
        { id: 'format/pick-up-object-style', label: 'Pick Up Object Style', shortcut: '⇧⌘C' },
        { id: 'format/apply-object-style', label: 'Apply Object Style', shortcut: '⇧⌘V' },
        { id: 'format/animation-painter', label: 'Animation Painter', shortcut: '⌥⇧⌘C' },
        '-',
        { id: 'format/replace-fonts', label: 'Replace Fonts...' },
        '-',
        { id: 'format/theme-colors', label: 'Theme Colors...' },
        { id: 'format/slide-background', label: 'Slide Background...', shortcut: '⇧⌘2' },
        '-',
        { id: 'format/crop', label: 'Crop', shortcut: '⇧C' },
        '-',
        { id: 'format/format-object', label: 'Format Object...', shortcut: '⇧⌘1' },
      ],
    },
    {
      id: 'arrange',
      label: 'Arrange',
      items: [
        { id: 'arrange/reorder-objects', label: 'Reorder Objects' },
        { id: 'arrange/reorder-overlapping-objects', label: 'Reorder Overlapping Objects' },
        '-',
        { id: 'arrange/bring-to-front', label: 'Bring to Front', shortcut: '⇧⌘F' },
        { id: 'arrange/send-to-back', label: 'Send to Back', shortcut: '⇧⌘B' },
        { id: 'arrange/bring-forward', label: 'Bring Forward', shortcut: '⌥⇧⌘F' },
        { id: 'arrange/send-backward', label: 'Send Backward', shortcut: '⌥⇧⌘B' },
        '-',
        { id: 'arrange/group', label: 'Group', shortcut: '⌥⌘G' },
        { id: 'arrange/ungroup', label: 'Ungroup', shortcut: '⌥⇧⌘G' },
        { id: 'arrange/regroup', label: 'Regroup', shortcut: '⌥⌘J' },
        '-',
        {
          id: 'arrange/rotate-or-flip',
          label: 'Rotate or Flip',
          children: [
            { id: 'arrange/rotate-or-flip/rotate-left-90', label: 'Rotate Left 90°' },
            { id: 'arrange/rotate-or-flip/rotate-right-90', label: 'Rotate Right 90°' },
            { id: 'arrange/rotate-or-flip/flip-horizontal', label: 'Flip Horizontal' },
            { id: 'arrange/rotate-or-flip/flip-vertical', label: 'Flip Vertical' },
            '-',
            {
              id: 'arrange/rotate-or-flip/more-rotation-options',
              label: 'More Rotation Options...',
            },
          ],
        },
        {
          id: 'arrange/align-or-distribute',
          label: 'Align or Distribute',
          children: [
            { id: 'arrange/align-or-distribute/align-left', label: 'Align Left' },
            { id: 'arrange/align-or-distribute/align-center', label: 'Align Center' },
            { id: 'arrange/align-or-distribute/align-right', label: 'Align Right' },
            { id: 'arrange/align-or-distribute/align-top', label: 'Align Top' },
            { id: 'arrange/align-or-distribute/align-middle', label: 'Align Middle' },
            { id: 'arrange/align-or-distribute/align-bottom', label: 'Align Bottom' },
            '-',
            {
              id: 'arrange/align-or-distribute/distribute-horizontally',
              label: 'Distribute Horizontally',
            },
            {
              id: 'arrange/align-or-distribute/distribute-vertically',
              label: 'Distribute Vertically',
            },
            '-',
            { id: 'arrange/align-or-distribute/align-to-slide', label: 'Align to Slide' },
            {
              id: 'arrange/align-or-distribute/align-selected-objects',
              label: 'Align Selected Objects',
            },
          ],
        },
        '-',
        { id: 'arrange/selection-pane', label: 'Selection Pane...', shortcut: '⌥⌘U' },
      ],
    },
    {
      id: 'tools',
      label: 'Tools',
      items: [
        { id: 'tools/spelling', label: 'Spelling...' },
        { id: 'tools/thesaurus', label: 'Thesaurus...', shortcut: '⌃⌥⌘R' },
        { id: 'tools/translate', label: 'Translate...' },
        { id: 'tools/set-proofing-language', label: 'Set Proofing Language...' },
        { id: 'tools/autocorrect-options', label: 'AutoCorrect Options...' },
        '-',
        { id: 'tools/check-accessibility', label: 'Check Accessibility' },
        '-',
        {
          id: 'tools/macro',
          label: 'Macro',
          children: [
            { id: 'tools/macro/macros', label: 'Macros...' },
            { id: 'tools/macro/visual-basic-editor', label: 'Visual Basic Editor' },
          ],
        },
        { id: 'tools/add-ins', label: 'Add-ins...' },
      ],
    },
    {
      id: 'slide-show',
      label: 'Slide Show',
      items: [
        { id: 'slide-show/play-from-start', label: 'Play from Start', shortcut: '⇧⌘↩' },
        {
          id: 'slide-show/play-from-current-slide',
          label: 'Play from Current Slide',
          shortcut: '⌘↩',
        },
        '-',
        {
          id: 'slide-show/custom-slide-show',
          label: 'Custom Slide Show',
          children: [{ id: 'slide-show/custom-slide-show/custom-shows', label: 'Custom Shows' }],
        },
        '-',
        { id: 'slide-show/rehearse-with-coach', label: 'Rehearse with Coach' },
        '-',
        { id: 'slide-show/presenter-view', label: 'Presenter View', shortcut: '⌥↩' },
        { id: 'slide-show/rehearse-timings', label: 'Rehearse Timings' },
        { id: 'slide-show/record-slide-show', label: 'Record Slide Show' },
        '-',
        { id: 'slide-show/hide-slide', label: 'Hide Slide' },
        { id: 'slide-show/set-up-show', label: 'Set Up Show...' },
        '-',
        { id: 'slide-show/always-use-subtitles', label: 'Always Use Subtitles' },
        {
          id: 'slide-show/subtitle-settings',
          label: 'Subtitle Settings',
          children: [
            {
              id: 'slide-show/subtitle-settings/spoken-language',
              label: 'Spoken Language',
              children: [],
            },
            {
              id: 'slide-show/subtitle-settings/subtitle-language',
              label: 'Subtitle Language',
              children: [],
            },
            '-',
            { id: 'slide-show/subtitle-settings/microphone', label: 'Microphone', children: [] },
            '-',
            { id: 'slide-show/subtitle-settings/bottom-overlaid', label: 'Bottom (Overlaid)' },
            { id: 'slide-show/subtitle-settings/top-overlaid', label: 'Top (Overlaid)' },
            { id: 'slide-show/subtitle-settings/below-slide', label: 'Below Slide' },
            { id: 'slide-show/subtitle-settings/above-slide', label: 'Above Slide' },
            '-',
            {
              id: 'slide-show/subtitle-settings/system-caption-preferences',
              label: 'System Caption Preferences...',
            },
          ],
        },
      ],
    },
    {
      id: 'window',
      label: 'Window',
      items: [
        { id: 'window/minimize', label: 'Minimize', shortcut: '⌘M' },
        { id: 'window/minimize-all', label: 'Minimize All' },
        { id: 'window/zoom', label: 'Zoom' },
        { id: 'window/zoom-all', label: 'Zoom All' },
        { id: 'window/fill', label: 'Fill', shortcut: '🌐⌃F' },
        { id: 'window/center', label: 'Center', shortcut: '🌐⌃C' },
        '-',
        {
          id: 'window/move-and-resize',
          label: 'Move & Resize',
          children: [
            { id: 'window/move-and-resize/halves', label: 'Halves' },
            { id: 'window/move-and-resize/left', label: 'Left' },
            { id: 'window/move-and-resize/right', label: 'Right' },
            { id: 'window/move-and-resize/top', label: 'Top' },
            { id: 'window/move-and-resize/bottom', label: 'Bottom' },
            '-',
            { id: 'window/move-and-resize/quarters', label: 'Quarters' },
            { id: 'window/move-and-resize/top-left', label: 'Top Left' },
            { id: 'window/move-and-resize/top-right', label: 'Top Right' },
            { id: 'window/move-and-resize/bottom-left', label: 'Bottom Left' },
            { id: 'window/move-and-resize/bottom-right', label: 'Bottom Right' },
            '-',
            { id: 'window/move-and-resize/arrange', label: 'Arrange' },
            { id: 'window/move-and-resize/left-and-right', label: 'Left & Right' },
            { id: 'window/move-and-resize/left-and-quarters', label: 'Left & Quarters' },
            { id: 'window/move-and-resize/right-and-left', label: 'Right & Left' },
            { id: 'window/move-and-resize/right-and-quarters', label: 'Right & Quarters' },
            { id: 'window/move-and-resize/top-and-bottom', label: 'Top & Bottom' },
            { id: 'window/move-and-resize/top-and-quarters', label: 'Top & Quarters' },
            { id: 'window/move-and-resize/bottom-and-top', label: 'Bottom & Top' },
            { id: 'window/move-and-resize/bottom-and-quarters', label: 'Bottom & Quarters' },
            { id: 'window/move-and-resize/quarters-2', label: 'Quarters' },
            '-',
            {
              id: 'window/move-and-resize/return-to-previous-size',
              label: 'Return to Previous Size',
              shortcut: '🌐⌃R',
            },
          ],
        },
        { id: 'window/full-screen-tile', label: 'Full Screen Tile' },
        '-',
        { id: 'window/remove-window-from-set', label: 'Remove Window from Set' },
        '-',
        { id: 'window/new-window', label: 'New Window' },
        { id: 'window/arrange-all', label: 'Arrange All' },
        { id: 'window/next-pane', label: 'Next Pane' },
        '-',
        { id: 'window/bring-all-to-front', label: 'Bring All to Front' },
        { id: 'window/arrange-in-front', label: 'Arrange in Front' },
        '-',
        { id: 'window/document', label: 'Presentation1' },
      ],
    },
    {
      id: 'help',
      label: 'Help',
      items: [
        { id: 'help/editor-help', label: 'Editor Help', shortcut: '⌘?' },
        '-',
        { id: 'help/feedback', label: 'Feedback' },
        '-',
        { id: 'help/clear-application-data', label: 'Clear Application Data' },
        '-',
        { id: 'help/check-for-updates', label: 'Check for Updates' },
      ],
    },
  ],
  ja: [
    {
      id: 'file',
      label: 'ファイル',
      items: [
        { id: 'file/new-presentation', label: '新規作成', shortcut: '⌘N' },
        { id: 'file/new-from-template', label: 'テンプレートから新規作成...', shortcut: '⇧⌘P' },
        { id: 'file/open', label: '開く...', shortcut: '⌘O' },
        {
          id: 'file/open-recent',
          label: '最近使ったファイル',
          children: [{ id: 'file/open-recent/more', label: 'その他...', shortcut: '⇧⌘O' }],
        },
        '-',
        { id: 'file/close', label: '閉じる', shortcut: '⌘W' },
        { id: 'file/save', label: '保存', shortcut: '⌘S' },
        { id: 'file/save-as', label: '名前を付けて保存...', shortcut: '⇧⌘S' },
        { id: 'file/save-as-template', label: 'テンプレートとして保存...' },
        { id: 'file/export', label: 'エクスポート...' },
        { id: 'file/move', label: '移動...' },
        { id: 'file/rename', label: '名前の変更...' },
        '-',
        { id: 'file/browse-version-history', label: 'バージョン履歴の表示' },
        '-',
        {
          id: 'file/share',
          label: '共有',
          children: [
            { id: 'file/share/share', label: '共有...' },
            '-',
            { id: 'file/share/send-presentation', label: 'プレゼンテーションを送信' },
            { id: 'file/share/send-pdf', label: 'PDF を送信' },
          ],
        },
        '-',
        { id: 'file/always-open-read-only', label: '常に読み取り専用で開く' },
        { id: 'file/restrict-permissions', label: 'アクセスの制限', children: [] },
        { id: 'file/passwords', label: 'パスワード...' },
        '-',
        { id: 'file/compress-pictures', label: '図の圧縮...' },
        '-',
        { id: 'file/page-setup', label: 'ページ設定...' },
        { id: 'file/print', label: 'プリント...', shortcut: '⌘P' },
        '-',
        { id: 'file/properties', label: 'プロパティ' },
      ],
    },
    {
      id: 'edit',
      label: '編集',
      items: [
        { id: 'edit/undo', label: '元に戻す 図の挿入', shortcut: '⌘Z' },
        { id: 'edit/repeat', label: '繰り返しできません', shortcut: '⌘Y' },
        '-',
        { id: 'edit/cut', label: 'カット', shortcut: '⌘X' },
        { id: 'edit/copy', label: 'コピー', shortcut: '⌘C' },
        '-',
        { id: 'edit/paste', label: 'ペースト', shortcut: '⌘V' },
        { id: 'edit/paste-special', label: '形式を選択してペースト...', shortcut: '⌃⌘V' },
        {
          id: 'edit/paste-and-match-formatting',
          label: 'ペーストしてスタイルを合わせる',
          shortcut: '⌥⇧⌘V',
        },
        '-',
        { id: 'edit/clear', label: 'クリア' },
        { id: 'edit/select-all', label: 'すべてを選択', shortcut: '⌘A' },
        { id: 'edit/duplicate', label: '複製', shortcut: '⌘D' },
        { id: 'edit/delete-slide', label: 'スライドの削除' },
        '-',
        { id: 'edit/remove-section', label: 'セクションの削除' },
        { id: 'edit/rename-section', label: 'セクション名の変更' },
        '-',
        {
          id: 'edit/find',
          label: '検索',
          children: [
            { id: 'edit/find/find', label: '検索...', shortcut: '⌘F' },
            { id: 'edit/find/find-next', label: '次を検索', shortcut: '⌘G' },
            { id: 'edit/find/find-previous', label: '前を検索', shortcut: '⇧⌘G' },
            { id: 'edit/find/advanced-find', label: '高度な検索...', shortcut: '⌃F' },
            '-',
            { id: 'edit/find/replace', label: '置換...', shortcut: '⌃H' },
            { id: 'edit/find/replace-fonts', label: 'フォントの置換...' },
          ],
        },
        { id: 'edit/select-data', label: 'データの選択...' },
        '-',
        { id: 'edit/toggle-drawing', label: '描画の切り替え', shortcut: '⌃⌘Z' },
        '-',
        {
          id: 'edit/autofill',
          label: '自動入力',
          children: [
            { id: 'edit/autofill/contact', label: '連絡先…' },
            { id: 'edit/autofill/passwords', label: 'パスワード…' },
            { id: 'edit/autofill/credit-card', label: 'クレジットカード…' },
          ],
        },
        { id: 'edit/start-dictation', label: '音声入力を開始', shortcut: '🎤' },
        { id: 'edit/emoji-and-symbols', label: '絵文字と記号', shortcut: '🌐' },
      ],
    },
    {
      id: 'view',
      label: '表示',
      items: [
        { id: 'view/normal', label: '標準', shortcut: '⌘1' },
        { id: 'view/slide-sorter', label: 'スライド一覧', shortcut: '⌘2' },
        { id: 'view/notes-page', label: 'ノート', shortcut: '⌘3' },
        { id: 'view/outline-view', label: 'アウトライン表示', shortcut: '⌘4' },
        { id: 'view/reading-view', label: '閲覧表示', shortcut: '⌘5' },
        { id: 'view/presenter-view', label: '発表者ツール', shortcut: '⌥↩' },
        { id: 'view/slide-show', label: 'スライド ショー', shortcut: '⇧⌘↩' },
        '-',
        { id: 'view/show-slides', label: 'アウトラインの表示', shortcut: '⌃⇧⇥' },
        '-',
        {
          id: 'view/master',
          label: 'マスター',
          children: [
            { id: 'view/master/slide-master', label: 'スライド マスター', shortcut: '⌥⌘1' },
            { id: 'view/master/handout-master', label: '配布資料マスター', shortcut: '⌥⌘2' },
            { id: 'view/master/notes-master', label: 'ノート マスター', shortcut: '⌥⌘3' },
          ],
        },
        '-',
        { id: 'view/ribbon', label: 'リボン', shortcut: '⌥⌘R' },
        { id: 'view/message-bar', label: 'メッセージ バー' },
        '-',
        { id: 'view/header-and-footer', label: 'ヘッダーとフッター...' },
        { id: 'view/markup', label: 'コメントと注釈' },
        { id: 'view/advanced-markup', label: '高度なマークアップ' },
        '-',
        { id: 'view/ruler', label: 'ルーラー' },
        {
          id: 'view/grid-and-guides',
          label: 'グリッドとガイド',
          children: [
            { id: 'view/grid-and-guides/smart-guides', label: 'スマート ガイド' },
            { id: 'view/grid-and-guides/guides', label: 'ガイド', shortcut: '⌃⌥⌘G' },
            { id: 'view/grid-and-guides/gridlines', label: 'グリッド線', shortcut: '⌘^' },
            '-',
            { id: 'view/grid-and-guides/snap-to-grid', label: 'グリッドに合わせる' },
            '-',
            { id: 'view/grid-and-guides/grid-options', label: 'グリッド オプション' },
          ],
        },
        {
          id: 'view/zoom',
          label: 'ズーム',
          children: [
            { id: 'view/zoom/fit-to-window', label: 'ウインドウに合わせる', shortcut: '⌥⌘O' },
            { id: 'view/zoom/zoom-in', label: 'ズーム イン', shortcut: '⌘+' },
            { id: 'view/zoom/zoom-out', label: 'ズーム アウト', shortcut: '⌘-' },
            '-',
            { id: 'view/zoom/zoom', label: 'ズーム...' },
          ],
        },
        { id: 'view/enter-full-screen', label: '全画面表示', shortcut: '🌐F' },
      ],
    },
    {
      id: 'insert',
      label: '挿入',
      items: [
        { id: 'insert/new-slide', label: '新しいスライド', shortcut: '⇧⌘N' },
        { id: 'insert/duplicate-slide', label: 'スライドの複製', shortcut: '⇧⌘D' },
        {
          id: 'insert/slides-from',
          label: 'スライドの指定',
          children: [
            { id: 'insert/slides-from/reuse-slides', label: 'スライドの再利用...' },
            { id: 'insert/slides-from/outline', label: 'アウトライン表示...' },
          ],
        },
        '-',
        { id: 'insert/section', label: 'セクション' },
        { id: 'insert/comment', label: 'コメント', shortcut: '⇧⌘M' },
        '-',
        { id: 'insert/wordart', label: 'ワードアート' },
        { id: 'insert/header-and-footer', label: 'ヘッダーとフッター...' },
        { id: 'insert/date-and-time', label: '日付と時刻...' },
        { id: 'insert/slide-number', label: 'スライド番号' },
        '-',
        { id: 'insert/table', label: '表...' },
        {
          id: 'insert/chart',
          label: 'グラフ',
          children: [
            { id: 'insert/chart/column', label: '縦棒' },
            { id: 'insert/chart/bar', label: '横棒' },
            { id: 'insert/chart/line', label: '折れ線' },
            { id: 'insert/chart/area', label: '面' },
            { id: 'insert/chart/pie', label: '円' },
            { id: 'insert/chart/treemap', label: 'ツリーマップ' },
            { id: 'insert/chart/sunburst', label: 'サンバースト' },
            { id: 'insert/chart/histogram', label: 'ヒストグラム' },
            { id: 'insert/chart/pareto', label: 'パレート図' },
            { id: 'insert/chart/box-and-whisker', label: '箱ひげ図' },
            { id: 'insert/chart/x-y-scatter', label: '散布図' },
            { id: 'insert/chart/waterfall', label: 'ウォーターフォール' },
            { id: 'insert/chart/funnel', label: 'じょうご' },
            { id: 'insert/chart/stock', label: '株価' },
            { id: 'insert/chart/surface', label: '等高線' },
            { id: 'insert/chart/radar', label: 'レーダー' },
            { id: 'insert/chart/filled-map', label: '塗り分けマップ' },
          ],
        },
        {
          id: 'insert/smartart',
          label: 'SmartArt',
          children: [
            { id: 'insert/smartart/list', label: 'リスト' },
            { id: 'insert/smartart/process', label: '手順' },
            { id: 'insert/smartart/cycle', label: '循環' },
            { id: 'insert/smartart/hierarchy', label: '階層構造' },
            { id: 'insert/smartart/relationship', label: '集合関係' },
            { id: 'insert/smartart/matrix', label: 'マトリックス' },
            { id: 'insert/smartart/pyramid', label: 'ピラミッド' },
            { id: 'insert/smartart/picture', label: '図' },
            { id: 'insert/smartart/timeline', label: 'タイムライン' },
            { id: 'insert/smartart/meet-the-team', label: 'チームに会う' },
            { id: 'insert/smartart/text-card', label: 'テキスト カード' },
          ],
        },
        '-',
        {
          id: 'insert/picture',
          label: '画像',
          children: [
            { id: 'insert/picture/photo-browser', label: '写真ブラウザー…' },
            { id: 'insert/picture/picture-from-file', label: '画像をファイルから挿入...' },
            { id: 'insert/picture/stock-images', label: 'ストック画像...' },
            { id: 'insert/picture/online-pictures', label: 'オンライン画像...' },
            { id: 'insert/picture/brand-images', label: 'ブランド イメージ...' },
          ],
        },
        {
          id: 'insert/audio',
          label: 'オーディオ',
          children: [
            { id: 'insert/audio/audio-browser', label: 'サウンド ブラウザー...' },
            { id: 'insert/audio/audio-from-file', label: 'オーディーをファイルから挿入...' },
            '-',
            { id: 'insert/audio/record-audio', label: 'オーディオの録音...' },
          ],
        },
        {
          id: 'insert/video',
          label: 'ビデオ',
          children: [
            { id: 'insert/video/movie-browser', label: 'ムービー ブラウザー...' },
            { id: 'insert/video/movie-from-file', label: 'ファイルからムービー...' },
            { id: 'insert/video/stock-videos', label: 'ストック ビデオ...' },
            { id: 'insert/video/online-movie', label: 'オンライン ビデオ...' },
          ],
        },
        { id: 'insert/cameo', label: 'レリーフ' },
        { id: 'insert/equation', label: '数式' },
        { id: 'insert/symbol', label: '記号/文字...' },
        {
          id: 'insert/shape',
          label: '図形',
          children: [
            { id: 'insert/shape/rectangle', label: '正方形/長方形' },
            { id: 'insert/shape/rounded-rectangle', label: '角丸四角形' },
            { id: 'insert/shape/triangle', label: '三角形' },
            { id: 'insert/shape/oval', label: '円/楕円' },
            { id: 'insert/shape/line', label: '線' },
          ],
        },
        '-',
        { id: 'insert/icons', label: 'アイコン...' },
        '-',
        {
          id: 'insert/3d-models',
          label: '3D モデル',
          children: [
            { id: 'insert/3d-models/insert-3d-model-from', label: '3D モデルを挿入' },
            { id: 'insert/3d-models/stock-3d-models', label: '3D モデルのストック...' },
            { id: 'insert/3d-models/this-device', label: 'このデバイス...' },
          ],
        },
        '-',
        {
          id: 'insert/zoom',
          label: 'ズーム',
          children: [
            { id: 'insert/zoom/summary-zoom', label: 'サマリー ズーム' },
            { id: 'insert/zoom/section-zoom', label: 'セクション ズーム' },
            { id: 'insert/zoom/slide-zoom', label: 'スライド ズーム' },
          ],
        },
        '-',
        {
          id: 'insert/action-buttons',
          label: '動作設定ボタン',
          children: [
            { id: 'insert/action-buttons/action-buttons', label: '動作設定ボタン' },
            { id: 'insert/action-buttons/back-or-previous', label: '戻る/前へ' },
            { id: 'insert/action-buttons/forward-or-next', label: '進む/次へ' },
            { id: 'insert/action-buttons/beginning', label: '先頭' },
            { id: 'insert/action-buttons/end', label: '終了' },
            { id: 'insert/action-buttons/home', label: 'ホーム' },
            { id: 'insert/action-buttons/information', label: '情報' },
            { id: 'insert/action-buttons/return', label: 'Return キー' },
            { id: 'insert/action-buttons/movie', label: 'ムービー' },
            { id: 'insert/action-buttons/document', label: '文書' },
            { id: 'insert/action-buttons/sound', label: 'サウンド' },
            { id: 'insert/action-buttons/help', label: 'ヘルプ' },
            { id: 'insert/action-buttons/custom', label: 'ユーザー定義' },
          ],
        },
        { id: 'insert/action-settings', label: 'オブジェクトの動作設定...' },
        '-',
        { id: 'insert/object', label: 'オブジェクト...' },
        { id: 'insert/hyperlink', label: 'ハイパーリンク...', shortcut: '⌘K' },
      ],
    },
    {
      id: 'format',
      label: 'フォーマット',
      items: [
        { id: 'format/font', label: 'フォント...', shortcut: '⌘T' },
        { id: 'format/paragraph', label: '段落...', shortcut: '⌥⌘M' },
        '-',
        { id: 'format/bullets-and-numbering', label: '箇条書きと段落番号...' },
        '-',
        { id: 'format/columns', label: '段組み...' },
        {
          id: 'format/alignment',
          label: '配置',
          children: [
            { id: 'format/alignment/align-left', label: '左揃え', shortcut: '⌘L' },
            { id: 'format/alignment/center', label: '中央揃え', shortcut: '⌘E' },
            { id: 'format/alignment/align-right', label: '右揃え', shortcut: '⌘R' },
            { id: 'format/alignment/justify', label: '両端揃え' },
            { id: 'format/alignment/distributed', label: '均等割り付け' },
          ],
        },
        { id: 'format/more-options', label: 'その他のオプション...' },
        '-',
        {
          id: 'format/pick-up-object-style',
          label: 'オブジェクト スタイルのコピー',
          shortcut: '⌥⌘C',
        },
        { id: 'format/apply-object-style', label: 'オブジェクト スタイルの適用', shortcut: '⇧⌘V' },
        {
          id: 'format/animation-painter',
          label: 'アニメーションのコピー/貼り付け',
          shortcut: '⌥⇧⌘C',
        },
        '-',
        { id: 'format/replace-fonts', label: 'フォントの置換...' },
        '-',
        { id: 'format/theme-colors', label: 'テーマの配色...' },
        { id: 'format/slide-background', label: 'スライドの背景...', shortcut: '⇧⌘2' },
        '-',
        { id: 'format/crop', label: 'トリミング', shortcut: '⇧C' },
        '-',
        { id: 'format/format-object', label: 'オブジェクトの書式設定...', shortcut: '⇧⌘1' },
      ],
    },
    {
      id: 'arrange',
      label: '配置',
      items: [
        { id: 'arrange/reorder-objects', label: 'オブジェクトの並べ替え' },
        { id: 'arrange/reorder-overlapping-objects', label: '重なり合ったオブジェクトの並べ替え' },
        '-',
        { id: 'arrange/bring-to-front', label: '最前面へ移動', shortcut: '⇧⌘F' },
        { id: 'arrange/send-to-back', label: '最背面へ移動', shortcut: '⇧⌘B' },
        { id: 'arrange/bring-forward', label: '前面へ移動', shortcut: '⌥⇧⌘F' },
        { id: 'arrange/send-backward', label: '背面へ移動', shortcut: '⌥⇧⌘B' },
        '-',
        { id: 'arrange/group', label: 'グループ化', shortcut: '⌥⌘G' },
        { id: 'arrange/ungroup', label: 'グループ解除', shortcut: '⌥⇧⌘G' },
        { id: 'arrange/regroup', label: '再グループ化', shortcut: '⌥⌘J' },
        '-',
        {
          id: 'arrange/rotate-or-flip',
          label: '回転/反転',
          children: [
            { id: 'arrange/rotate-or-flip/rotate-left-90', label: '左へ 90 度回転' },
            { id: 'arrange/rotate-or-flip/rotate-right-90', label: '右へ 90 度回転' },
            { id: 'arrange/rotate-or-flip/flip-horizontal', label: '左右反転' },
            { id: 'arrange/rotate-or-flip/flip-vertical', label: '上下反転' },
            '-',
            {
              id: 'arrange/rotate-or-flip/more-rotation-options',
              label: 'その他の回転オプション...',
            },
          ],
        },
        {
          id: 'arrange/align-or-distribute',
          label: '配置/整列',
          children: [
            { id: 'arrange/align-or-distribute/align-left', label: '左揃え' },
            { id: 'arrange/align-or-distribute/align-center', label: '左右中央揃え' },
            { id: 'arrange/align-or-distribute/align-right', label: '右揃え' },
            { id: 'arrange/align-or-distribute/align-top', label: '上揃え' },
            { id: 'arrange/align-or-distribute/align-middle', label: '上下中央揃え' },
            { id: 'arrange/align-or-distribute/align-bottom', label: '下揃え' },
            '-',
            { id: 'arrange/align-or-distribute/distribute-horizontally', label: '左右に整列' },
            { id: 'arrange/align-or-distribute/distribute-vertically', label: '上下に整列' },
            '-',
            { id: 'arrange/align-or-distribute/align-to-slide', label: 'スライドに合わせて配置' },
            {
              id: 'arrange/align-or-distribute/align-selected-objects',
              label: '選択したオブジェクトの配置',
            },
          ],
        },
        '-',
        { id: 'arrange/selection-pane', label: '選択ウインドウ...', shortcut: '⌥⌘U' },
      ],
    },
    {
      id: 'tools',
      label: 'ツール',
      items: [
        { id: 'tools/spelling', label: 'スペル チェック...' },
        { id: 'tools/thesaurus', label: '類義語辞典...', shortcut: '⌃⌥⌘R' },
        { id: 'tools/translate', label: '翻訳...' },
        { id: 'tools/set-proofing-language', label: '校正言語の設定...' },
        { id: 'tools/autocorrect-options', label: 'オートコレクトのオプション...' },
        '-',
        { id: 'tools/check-accessibility', label: 'アクセシビリティ チェック' },
        '-',
        {
          id: 'tools/macro',
          label: 'マクロ',
          children: [
            { id: 'tools/macro/macros', label: 'マクロ...' },
            { id: 'tools/macro/visual-basic-editor', label: 'Visual Basic Editor' },
          ],
        },
        { id: 'tools/add-ins', label: 'アドイン' },
      ],
    },
    {
      id: 'slide-show',
      label: 'スライド ショー',
      items: [
        { id: 'slide-show/play-from-start', label: '最初から再生', shortcut: '⇧⌘↩' },
        {
          id: 'slide-show/play-from-current-slide',
          label: '現在のスライドから再生',
          shortcut: '⌘↩',
        },
        '-',
        {
          id: 'slide-show/custom-slide-show',
          label: '目的別スライド ショー',
          children: [
            { id: 'slide-show/custom-slide-show/custom-shows', label: '目的別スライド ショー' },
          ],
        },
        '-',
        { id: 'slide-show/presenter-view', label: '発表者ツール', shortcut: '⌥↩' },
        { id: 'slide-show/rehearse-timings', label: 'リハーサル' },
        { id: 'slide-show/record-slide-show', label: 'スライド ショーの記録' },
        '-',
        { id: 'slide-show/hide-slide', label: '非表示スライドに設定' },
        { id: 'slide-show/set-up-show', label: 'スライド ショーの設定...' },
        '-',
        { id: 'slide-show/always-use-subtitles', label: '常に字幕を使用する' },
        {
          id: 'slide-show/subtitle-settings',
          label: '字幕の設定',
          children: [
            {
              id: 'slide-show/subtitle-settings/spoken-language',
              label: '話し手の言語',
              children: [],
            },
            {
              id: 'slide-show/subtitle-settings/subtitle-language',
              label: '字幕の言語',
              children: [],
            },
            '-',
            { id: 'slide-show/subtitle-settings/microphone', label: 'マイク', children: [] },
            '-',
            { id: 'slide-show/subtitle-settings/bottom-overlaid', label: '下部 (重ねて表示)' },
            { id: 'slide-show/subtitle-settings/top-overlaid', label: '上部 (重ねて表示)' },
            { id: 'slide-show/subtitle-settings/below-slide', label: 'スライドの下' },
            { id: 'slide-show/subtitle-settings/above-slide', label: 'スライドの上' },
            '-',
            {
              id: 'slide-show/subtitle-settings/system-caption-preferences',
              label: 'システムのキャプション設定...',
            },
          ],
        },
      ],
    },
    {
      id: 'window',
      label: 'ウィンドウ',
      items: [
        { id: 'window/minimize', label: 'しまう', shortcut: '⌘M' },
        { id: 'window/zoom', label: 'ズーム' },
        '-',
        { id: 'window/new-window', label: '新しいウインドウを開く' },
        { id: 'window/arrange-all', label: 'ウインドウの整列' },
        { id: 'window/next-pane', label: '次のペイン' },
        '-',
        { id: 'window/bring-all-to-front', label: 'すべてを手前に移動' },
        { id: 'window/minimize-all', label: 'すべてをしまう' },
        { id: 'window/zoom-all', label: 'すべてを拡大/縮小' },
        { id: 'window/fill', label: '画面全体に表示', shortcut: '🌐⌃F' },
        { id: 'window/center', label: '中央に配置', shortcut: '🌐⌃C' },
        '-',
        {
          id: 'window/move-and-resize',
          label: '移動とサイズ変更',
          children: [
            { id: 'window/move-and-resize/halves', label: '2分割' },
            { id: 'window/move-and-resize/left', label: '左' },
            { id: 'window/move-and-resize/right', label: '右' },
            { id: 'window/move-and-resize/top', label: '上' },
            { id: 'window/move-and-resize/bottom', label: '下' },
            '-',
            { id: 'window/move-and-resize/quarters', label: '4分割' },
            { id: 'window/move-and-resize/top-left', label: '左上' },
            { id: 'window/move-and-resize/top-right', label: '右上' },
            { id: 'window/move-and-resize/bottom-left', label: '左下' },
            { id: 'window/move-and-resize/bottom-right', label: '右下' },
            '-',
            { id: 'window/move-and-resize/arrange', label: '配置' },
            { id: 'window/move-and-resize/left-and-right', label: '左と右' },
            { id: 'window/move-and-resize/left-and-quarters', label: '左と4分割' },
            { id: 'window/move-and-resize/right-and-left', label: '右と左' },
            { id: 'window/move-and-resize/right-and-quarters', label: '右と4分割' },
            { id: 'window/move-and-resize/top-and-bottom', label: '上と下' },
            { id: 'window/move-and-resize/top-and-quarters', label: '上と4分割' },
            { id: 'window/move-and-resize/bottom-and-top', label: '下と上' },
            { id: 'window/move-and-resize/bottom-and-quarters', label: '下と4分割' },
            { id: 'window/move-and-resize/quarters-2', label: '4分割' },
            '-',
            {
              id: 'window/move-and-resize/return-to-previous-size',
              label: '前のサイズに戻す',
              shortcut: '🌐⌃R',
            },
          ],
        },
        { id: 'window/full-screen-tile', label: 'フルスクリーンのタイル表示' },
        '-',
        { id: 'window/remove-window-from-set', label: 'ウインドウをセットから削除' },
        { id: 'window/arrange-in-front', label: 'ウインドウを整理' },
        '-',
        { id: 'window/document', label: 'プレゼンテーション1' },
      ],
    },
    {
      id: 'help',
      label: 'ヘルプ',
      items: [
        { id: 'help/editor-help', label: 'エディター ヘルプ', shortcut: '⌘?' },
        '-',
        { id: 'help/feedback', label: 'フィードバック' },
        '-',
        { id: 'help/clear-application-data', label: 'アプリケーション データのクリア' },
        '-',
        { id: 'help/check-for-updates', label: '更新プログラムのチェック' },
      ],
    },
  ],
};
