// Unit coverage for the preview-fidelity metric core. These modules are
// dependency-free (no LibreOffice / resvg), so the math is gated in CI even
// though the full harness needs external renderers. See
// site/fidelity/README.md.

import { describe, expect, it } from 'vitest';
import { rgbToRgba, resizeRgba, type RgbaImage } from '../site/fidelity/image.ts';
import { compareImages, diffImage } from '../site/fidelity/ssim.ts';
import { decodePpm } from '../site/fidelity/ppm.ts';
import { encodePng } from '../site/fidelity/png.ts';

const solid = (w: number, h: number, r: number, g: number, b: number): RgbaImage => {
  const data = new Uint8Array(w * h * 4);
  for (let i = 0; i < w * h; i++) {
    data[i * 4] = r;
    data[i * 4 + 1] = g;
    data[i * 4 + 2] = b;
    data[i * 4 + 3] = 255;
  }
  return { width: w, height: h, data };
};

// Deterministic checkerboard so SSIM has structure to score, not a flat field.
const checker = (w: number, h: number, scale: number): RgbaImage => {
  const data = new Uint8Array(w * h * 4);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const on = (Math.floor(x / scale) + Math.floor(y / scale)) % 2 === 0;
      const v = on ? 230 : 25;
      const p = (y * w + x) * 4;
      data[p] = v;
      data[p + 1] = v;
      data[p + 2] = v;
      data[p + 3] = 255;
    }
  }
  return { width: w, height: h, data };
};

describe('compareImages', () => {
  it('scores identical images at SSIM 1', () => {
    const img = checker(32, 32, 4);
    const r = compareImages(img, img);
    expect(r.ssim).toBeCloseTo(1, 6);
    expect(r.meanAbsError).toBe(0);
    expect(r.diffPercent).toBe(0);
  });

  it('scores a structurally different image well below 1', () => {
    const a = checker(32, 32, 4);
    const b = checker(32, 32, 8); // different structure
    const r = compareImages(a, b);
    expect(r.ssim).toBeLessThan(0.7);
    expect(r.diffPercent).toBeGreaterThan(0);
  });

  it('scores an inverted image at the floor', () => {
    const a = solid(16, 16, 255, 255, 255);
    const b = solid(16, 16, 0, 0, 0);
    const r = compareImages(a, b);
    expect(r.ssim).toBeLessThan(0.1);
    expect(r.meanAbsError).toBeCloseTo(1, 2);
    expect(r.diffPercent).toBe(1);
  });

  it('throws on dimension mismatch', () => {
    expect(() => compareImages(solid(4, 4, 0, 0, 0), solid(8, 8, 0, 0, 0))).toThrow(/mismatch/);
  });
});

describe('resizeRgba', () => {
  it('is a no-op at the same size', () => {
    const img = checker(8, 8, 2);
    expect(resizeRgba(img, 8, 8)).toBe(img);
  });

  it('resizes to the requested dimensions and stays comparable', () => {
    const img = checker(32, 32, 4);
    const up = resizeRgba(img, 64, 64);
    expect(up.width).toBe(64);
    expect(up.height).toBe(64);
    // A bilinear up/down round-trip should still look like the original.
    const back = resizeRgba(up, 32, 32);
    expect(compareImages(img, back).ssim).toBeGreaterThan(0.9);
  });
});

describe('ppm <-> png round-trips through the pixel buffer', () => {
  it('decodes a P6 PPM with a comment line', () => {
    const header = Buffer.from('P6\n# generated by test\n2 1\n255\n', 'ascii');
    const body = Buffer.from([10, 20, 30, 40, 50, 60]); // two RGB pixels
    const img = decodePpm(new Uint8Array(Buffer.concat([header, body])));
    expect(img.width).toBe(2);
    expect(img.height).toBe(1);
    expect([...img.data]).toEqual([10, 20, 30, 255, 40, 50, 60, 255]);
  });

  it('encodes a PNG with the signature and IEND', () => {
    const png = encodePng(solid(3, 2, 1, 2, 3));
    expect([...png.subarray(0, 8)]).toEqual([137, 80, 78, 71, 13, 10, 26, 10]);
    // IEND is the last 8 bytes: length 0 + "IEND" + crc.
    expect(String.fromCharCode(...png.subarray(png.length - 8, png.length - 4))).toBe('IEND');
  });

  it('round-trips RGB through rgbToRgba preserving channels', () => {
    const img = rgbToRgba(new Uint8Array([5, 6, 7]), 1, 1);
    expect([...img.data]).toEqual([5, 6, 7, 255]);
  });
});

describe('diffImage', () => {
  it('matches the input dimensions', () => {
    const d = diffImage(solid(10, 4, 0, 0, 0), solid(10, 4, 255, 255, 255));
    expect(d.width).toBe(10);
    expect(d.height).toBe(4);
    expect(d.data.length).toBe(10 * 4 * 4);
  });
});
