// Embedded-object API barrel.
export * from './comments.ts';
export * from './shape-image.ts';
export * from './shape-click-action.ts';
export * from './charts.ts';
export * from './tables.ts';
export * from './validation.ts';
export * from './package-introspection.ts';
export * from './shape-image-effects.ts';
export * from './shape-animation.ts';
export * from './slide-title.ts';
