/** Punch transparent gaps into compound strokes without painting over the fill. */
export function compoundStroke(
  geometry: string,
  compound: string | null,
  bounds: { x: number; y: number; w: number; h: number },
  width: number,
  id: string,
): string {
  const asymmetric = compound === 'thickThin' || compound === 'thinThick';
  if ((compound !== 'dbl' && compound !== 'tri' && !asymmetric) || width <= 0) return geometry;
  // This markup is generated by our geometry renderer. Only geometry carrying
  // an explicit non-empty stroke participates; fill-only custom paths retain it.
  let index = 0;
  const parts = geometry.replace(
    /<(path|rect|ellipse|polygon|line)\b([^>]*?)(?:\/>|>([\s\S]*?)<\/\1>)/g,
    (original, name: string, attributes: string, content: string | undefined) => {
      const tag = `<${name}${attributes}/>`;
      if (!/ stroke="(?!none")[^"]+"/.test(tag)) return original;
      // A filled silhouette identifies the inside independently of winding.
      // Open paths need directional offsets instead; never close them implicitly.
      if (asymmetric && name !== 'rect' && name !== 'ellipse' && name !== 'polygon') {
        const d = attributes.match(/\bd="([^"]*)"/)?.[1];
        const subpaths = d?.split(/(?=[Mm])/).filter((part) => part.trim());
        if (!subpaths?.length || subpaths.some((part) => !/[Zz]\s*$/.test(part))) return original;
      }
      const withoutMarkers = tag.replace(/ marker-(?:start|end)="[^"]*"/g, '');
      const fillOnly = withoutMarkers.replace(/ stroke="[^"]*"/, ' stroke="none"');
      const outline = withoutMarkers.replace(/ fill="[^"]*"/, ' fill="none"');
      const maskShape = withoutMarkers
        .replace(/ fill="[^"]*"/, ' fill="none"')
        .replace(/ (?:stroke-opacity|fill-opacity)="[^"]*"/g, '');
      const band = (color: string, scale: number) =>
        maskShape
          .replace(/ stroke="[^"]*"/, ` stroke="${color}"`)
          .replace(/ stroke-width="[^"]*"/, ` stroke-width="${width * scale}"`)
          .replace(/\/?\s*>$/, '/>');
      // Each geometry element gets a separate mask so overlapping custom paths
      // cannot erase one another's outlines.
      const maskId = `${id}-${index++}`;
      const pad = width * 5;
      const clipId = `${maskId}-inside`;
      const silhouette = withoutMarkers
        .replace(/ fill="[^"]*"/, '')
        .replace(/ fill-rule="([^"]*)"/, ' fill-rule="$1" clip-rule="$1"')
        .replace(/ (?:stroke-opacity|fill-opacity)="[^"]*"/g, '')
        .replace(/ stroke="[^"]*"/, ' stroke="none" fill="white"');
      const clippedBand = (color: string) =>
        `<g clip-path="url(#${clipId})">${band(color, 1 / 2)}</g>`;
      const clip = asymmetric ? `<clipPath id="${clipId}">${silhouette}</clipPath>` : '';
      // Triple is thin/thick/thin: line/gap/line/gap/line = 1:1:2:1:1.
      // Erase the middle four units, then restore the central two units.
      // Asymmetric lines use 2:1:1 or 1:1:2 from outside to inside.
      const gaps = asymmetric
        ? compound === 'thickThin'
          ? clippedBand('black')
          : band('black', 1 / 2) + clippedBand('white')
        : band('black', compound === 'dbl' ? 1 / 3 : 2 / 3) +
          (compound === 'tri' ? band('white', 1 / 3) : '');
      const mask = `<mask id="${maskId}" maskUnits="userSpaceOnUse" x="${bounds.x - pad}" y="${bounds.y - pad}" width="${bounds.w + pad * 2}" height="${bounds.h + pad * 2}" style="mask-type:luminance">${band('white', 1)}${gaps}</mask>`;
      const masked = outline.replace(/\/?\s*>$/, ` mask="url(#${maskId})"/>`);
      const fillMarkup = content ? fillOnly.replace(/\/>$/, `>${content}</${name}>`) : fillOnly;
      const arrows = / marker-(?:start|end)=/.test(tag)
        ? tag.replace(/ stroke="[^"]*"/, ' stroke="none"').replace(/ fill="[^"]*"/, ' fill="none"')
        : '';
      return `<defs>${clip}${mask}</defs>${fillMarkup}${masked}${arrows}`;
    },
  );
  return parts;
}
