// Public API surface. The only directory users are intended to import from.
//
// Two parallel APIs are exposed:
//
//   1. The class-based API (`Presentation`, `Slide`, `SlideShape`,
//      `SlideLayout`) — convenient, fluent, and what existing tests use.
//   2. The tree-shakeable free-function API (`loadPresentation`,
//      `savePresentation`, `createPresentation`, ...) — importing only
//      what you use lets modern bundlers drop the class definitions. See
//      `test/tree-shake.test.ts` for the CI guard.
//
// Both APIs operate on the same opaque internal state, so values produced
// by one can flow into the other.

export { type Emu, cm, emu, inches, mm, pt } from './units.ts';

// Class-based legacy API.
export { Presentation, type PresentationInput, _internalPackageOf } from './presentation.ts';
export { type PlaceholderType, Slide, SlideShape } from './slide.ts';
export { SlideLayout } from './slide-layout.ts';

// Tree-shakeable free-function API.
export type {
  PresentationData,
  SlideCommentData,
  SlideData,
  SlideLayoutData,
  SlideShapeData,
  TableCellData,
} from './_internal-symbols.ts';
export type {
  CommentAuthor,
  CommentPosition,
  SlideComment,
} from '../internal/presentationml/index.ts';
export type { SlideSize } from './fn.ts';
export { SLIDE_SIZE_4_3, SLIDE_SIZE_16_9, SLIDE_SIZE_16_10 } from './fn.ts';
export type { ImageFormat } from '../internal/opc/index.ts';
export type { ChartKind, ChartSeries, ChartSpec } from '../internal/chartml/index.ts';
export type { SlideChartData } from './fn.ts';
export type { ShapeClickAction } from './fn.ts';
export type { IssueSeverity, ValidationIssue } from './fn.ts';
export type { AnimationEffect, AnimationOptions } from './fn.ts';
export type { ImageCrop } from './fn.ts';
export type {
  ArrowOptions,
  GlowOptions,
  GradientFillOptions,
  GradientStop,
  LineDash,
  LineEndSize,
  LineEndType,
  PatternFillOptions,
  PatternPreset,
  ShadowOptions,
} from '../internal/drawingml/index.ts';
export type {
  AllShapesEntry,
  CoreProperties,
  ExtendedProperties,
  MediaPart,
  PackagePartInfo,
  PresentationChartEntry,
  PresentationCommentEntry,
  PresentationFonts,
  PresentationHyperlinkEntry,
  PresentationImageEntry,
  PresentationNotesEntry,
  PresentationSummary,
  PresentationTableEntry,
  PresentationTheme,
  PresentationThumbnail,
  ShapeBounds,
  ShapeEffect,
  ShapeFill,
  ShapeStroke,
  SlideBackground,
  SlideInfo,
  SlideLayoutPlaceholder,
  SlideOutlineEntry,
  SlideSection,
  TextAnchor,
  TextAutoFit,
  TextWrap,
} from './fn.ts';
export {
  addBlankSlide,
  addContentSlide,
  addSectionHeaderSlide,
  addSlide,
  addSlideAt,
  addSlideChart,
  bringShapeForward,
  bringShapeToFront,
  centerShapeOnSlide,
  addSlideComment,
  addSlideImage,
  addSlideLine,
  addSlideShape,
  addSlideTable,
  addSlideTextBox,
  addTitleSlide,
  appendShapeText,
  appendSlideNotes,
  clearShapeEffects,
  clearShapeFill,
  clearAllAnimations,
  clearAllSlideBackgrounds,
  clearAllTransitions,
  clearShapeStroke,
  clearShapeText,
  clearSlideAnimations,
  clearSlideBackground,
  clearSlideShapes,
  clearSlideTransition,
  clearTableCellFill,
  compactPackage,
  copyShape,
  createPresentation,
  duplicateSlide,
  duplicateSlideAt,
  findChartByKind,
  findChartsBySeriesName,
  findCommentsByAuthor,
  findEmptyPlaceholders,
  findLayoutsWithPlaceholderType,
  findFlippedShapes,
  findHyperlinkedShapes,
  findOverlappingShapePairs,
  findRotatedShapes,
  findShapeById,
  findShapeByName,
  findShapeByText,
  findShapeInPresentation,
  findShapesByKind,
  findShapesByName,
  findShapesAtPoint,
  findShapesByText,
  findShapesOutsideCanvas,
  findShapesWithImages,
  findShapesWithText,
  findSlideByPartName,
  findSlideByText,
  findSlideByTitle,
  findSlideLayout,
  findSlideLayoutByPartName,
  findSlideLayoutByType,
  findSlidePlaceholder,
  findSlidePlaceholderByIdx,
  findSlidePlaceholders,
  findSlidesByLayoutName,
  findSlidesByLayoutType,
  findSlidesByText,
  findSlidesWithCommentsByAuthor,
  findSlidesWithOverlap,
  getAllCharts,
  getAllComments,
  getAllHyperlinks,
  getAllImages,
  getAllNotes,
  getAllShapes,
  getAllTables,
  getCommentAuthor,
  getCommentAuthors,
  getCommentCount,
  getCommentDate,
  getCommentPosition,
  getCommentSlide,
  getCommentText,
  getCoreProperties,
  getDistinctHyperlinkUrls,
  getHiddenSlideCount,
  getHiddenSlides,
  getImageParts,
  getExtendedProperties,
  getParagraphAlignment,
  getParagraphBullet,
  getParagraphLevel,
  getParagraphSpacing,
  getShapeAltTitle,
  getShapeAnimation,
  getShapeAt,
  getShapeBounds,
  getShapeCenter,
  getShapeChartCategories,
  getShapeChartKind,
  getShapeChartSeriesNames,
  getShapeChartSeriesValues,
  getShapeChartSpec,
  getShapeCount,
  getShapeClickAction,
  getShapeDescription,
  getShapeEffect,
  getShapeFill,
  getShapeFillColor,
  getShapeFlip,
  getShapeHyperlink,
  getShapeId,
  getShapeImageBrightness,
  getShapeImageBytes,
  getShapeImageFillBytes,
  getShapeImageContrast,
  getShapeImageFormat,
  getShapeImagePartName,
  getShapeImageCrop,
  getShapeImageOpacity,
  getShapeIndex,
  getShapeKind,
  getShapeName,
  getShapeParagraphCount,
  getShapePlaceholderIdx,
  getMediaParts,
  getOrphanMediaPartNames,
  getOutlineText,
  getPackageSize,
  getPresentationCommenters,
  getPresentationCreated,
  getPresentationFonts,
  getPresentationModified,
  getPresentationSummary,
  getPresentationChartCount,
  getPresentationHyperlinkCount,
  getPresentationImageCount,
  getPresentationShapeCount,
  getPresentationTableCount,
  getPresentationText,
  getPresentationTextLength,
  getPresentationTheme,
  getShapePlaceholderType,
  getShapePosition,
  getShapeRotation,
  getShapeRunCount,
  getShapeRunFormat,
  getShapeRunHyperlink,
  getShapeRunText,
  getShapeSize,
  getShapesBounds,
  getShapeSlide,
  getShapeStroke,
  getShapeStrokeArrow,
  getShapeStrokeColor,
  getShapeStrokeDash,
  getShapeStrokeWidth,
  getShapeText,
  getShapeTextAnchor,
  getShapeTextAutoFit,
  getShapeTextMargins,
  getShapeTextWrap,
  getShapeXmlString,
  getShapeZIndex,
  getSlideAt,
  getSlideAuthors,
  getSlideBackground,
  getSlideBody,
  getSlideCharts,
  getSlideCommentCount,
  getSlideComments,
  getSlideCount,
  getSlideImageCount,
  getSlideIndex,
  getSlideInfo,
  getSlideLayout,
  getSlideLayoutCount,
  getSlideLayoutName,
  getSlideLayoutNames,
  getSlideLayoutPartName,
  getSlideLayoutPlaceholders,
  getSlideLayouts,
  getSlideLayoutType,
  getSlideLayoutTypes,
  getSlideMediaPartNames,
  getSlideNotes,
  getSlideOutline,
  getSlidePartName,
  getSlideSections,
  getSlideBoundingBox,
  getSlideShapeBounds,
  getSlideShapeIds,
  getSlideShapeKinds,
  getSlideShapeNames,
  getSlideShapeRotations,
  getSlideShapeTexts,
  getSlideShapes,
  getSlideSize,
  getSlideText,
  getSlideTextLength,
  getSlideTextShapeCount,
  getSlideTitle,
  getSlideTitles,
  getSlideTransition,
  getSlideXmlString,
  getSlides,
  getSlidesByLayout,
  getSlidesWithCharts,
  getSlidesWithComments,
  getSlidesWithEmptyPlaceholders,
  getSlidesWithImages,
  getSlidesWithNotes,
  getSlidesWithTables,
  getTableCell,
  getTableCellAlignment,
  getTableCellFill,
  getTableCellPosition,
  getTableCellText,
  hasShapeImage,
  getTableCells,
  getTableColumnWidths,
  getTableDimensions,
  getTableRowHeights,
  getTableSize,
  getThumbnail,
  getTotalShapeCount,
  getVisibleSlideCount,
  getVisibleSlides,
  hasShapeText,
  importSlide,
  incrementRevision,
  insertTableColumn,
  insertTableRow,
  isChartShape,
  isShapeHidden,
  isShapePlaceholder,
  isSlideHidden,
  isTableShape,
  listPackageParts,
  loadPresentation,
  mergePresentations,
  moveSlide,
  readPackagePart,
  removeShape,
  removeSlide,
  removeSlideComment,
  removeSlideNotes,
  removeThumbnail,
  removeTableColumn,
  removeTableRow,
  renameShape,
  replaceTextInPresentation,
  replaceTextInSlide,
  replaceTokensInPresentation,
  replaceTokensInSlide,
  reverseSlides,
  savePresentation,
  sendShapeBackward,
  sendShapeToBack,
  setChartSpec,
  setCoreProperties,
  setExtendedProperties,
  setAllSlidesBackground,
  setAllSlidesHidden,
  setAllSlidesTransition,
  setMediaPartBytes,
  setShapeAlignment,
  setShapeAltTitle,
  setShapeAnimation,
  setShapeBounds,
  setShapeBullets,
  setShapeFill,
  setShapeFlip,
  setShapeGlow,
  setShapeGradientFill,
  setShapeHidden,
  setShapeShadow,
  setShapeHyperlink,
  setShapeImage,
  setShapeImageBrightness,
  setShapeImageContrast,
  setShapeImageCrop,
  setShapeImageFill,
  setShapeImageOpacity,
  setShapeClickAction,
  setShapeDescription,
  setShapeNoFill,
  setShapeNoStroke,
  setShapePatternFill,
  setParagraphAlignment,
  setParagraphBullet,
  setParagraphLevel,
  setParagraphSpacing,
  setShapePosition,
  setShapeRotation,
  setShapeRunFormat,
  setShapeRunHyperlink,
  setShapeRunText,
  setShapeSize,
  setShapeStroke,
  setShapeStrokeArrow,
  setShapeStrokeDash,
  setShapeText,
  setShapeTextAnchor,
  setShapeTextAutoFit,
  setShapeTextFormat,
  setShapeTextMargins,
  setShapeTextWrap,
  setShapeZIndex,
  setSlideBackground,
  setSlideBackgroundImage,
  setSlideBody,
  setSlideHidden,
  setSlideLayout,
  setSlideNotes,
  setSlidePlaceholders,
  setSlideSections,
  setSlideSize,
  setSlideTitle,
  setSlideTransition,
  setTableCellAlignment,
  setTableCellFill,
  setTableCellText,
  setTableCellTextFormat,
  setTableColumnWidth,
  setTableRowHeight,
  setThumbnail,
  pointInShape,
  shapesOverlap,
  slidesUsingMediaPart,
  sortSlides,
  swapSlides,
  touchModified,
  translateShapes,
  validatePresentation,
} from './fn.ts';

export type { BulletStyle, ParagraphAlignment, TextFormat } from '../internal/drawingml/index.ts';
export type {
  PresetShape,
  TransitionEffect,
  TransitionOptions,
} from '../internal/presentationml/index.ts';

// Library version. Replaced at build time by the package version.
export const VERSION = '0.0.0';
