// Public API surface. The only directory users are intended to import from.
//
// Two parallel APIs are exposed:
//
//   1. The class-based API (`Presentation`, `Slide`, `SlideShape`,
//      `SlideLayout`) — convenient, fluent, and what existing tests use.
//   2. The tree-shakeable free-function API (`loadPresentation`,
//      `savePresentation`, `createPresentation`, ...) — importing only
//      what you use lets modern bundlers drop the class definitions. See
//      `test/tree-shake.test.ts` for the CI guard.
//
// Both APIs operate on the same opaque internal state, so values produced
// by one can flow into the other.

export { type Emu, cm, emu, inches, mm, pt } from './units.ts';

// Class-based legacy API.
export { Presentation, type PresentationInput, _internalPackageOf } from './presentation.ts';
export { type PlaceholderType, Slide, SlideShape } from './slide.ts';
export { SlideLayout } from './slide-layout.ts';

// Tree-shakeable free-function API.
export type {
  PresentationData,
  SlideCommentData,
  SlideData,
  SlideLayoutData,
  SlideShapeData,
  TableCellData,
} from './_internal-symbols.ts';
export type {
  CommentAuthor,
  CommentPosition,
  SlideComment,
} from '../internal/presentationml/index.ts';
export type { SlideSize } from './fn.ts';
export { SLIDE_SIZE_4_3, SLIDE_SIZE_16_9, SLIDE_SIZE_16_10 } from './fn.ts';
export type { ImageFormat } from '../internal/opc/index.ts';
export type { ChartKind, ChartSeries, ChartSpec } from '../internal/chartml/index.ts';
export type { SlideChartData } from './fn.ts';
export type { ShapeClickAction } from './fn.ts';
export type { IssueSeverity, ValidationIssue } from './fn.ts';
export type { AnimationEffect, AnimationOptions } from './fn.ts';
export type { ImageCrop } from './fn.ts';
export type {
  ArrowOptions,
  GlowOptions,
  GradientFillOptions,
  GradientStop,
  LineDash,
  LineEndSize,
  LineEndType,
  PatternFillOptions,
  PatternPreset,
  ShadowOptions,
} from '../internal/drawingml/index.ts';
export type {
  AllShapesEntry,
  MediaPart,
  PackagePartInfo,
  PresentationSummary,
  PresentationTheme,
  ShapeBounds,
  ShapeEffect,
  ShapeFill,
  ShapeStroke,
  SlideBackground,
  SlideInfo,
  SlideLayoutPlaceholder,
  SlideSection,
  TextAnchor,
  TextAutoFit,
  TextWrap,
} from './fn.ts';
export {
  addSlide,
  addSlideAt,
  addSlideChart,
  bringShapeForward,
  bringShapeToFront,
  addSlideComment,
  addSlideImage,
  addSlideLine,
  addSlideShape,
  addSlideTable,
  addSlideTextBox,
  clearShapeEffects,
  clearShapeFill,
  clearShapeStroke,
  clearSlideAnimations,
  clearSlideBackground,
  clearSlideShapes,
  clearSlideTransition,
  clearTableCellFill,
  compactPackage,
  copyShape,
  createPresentation,
  duplicateSlide,
  duplicateSlideAt,
  findShapeById,
  findShapeByName,
  findShapeInPresentation,
  findShapesByKind,
  findShapesByName,
  findSlideByText,
  findSlideLayout,
  findSlideLayoutByType,
  findSlidePlaceholder,
  findSlidesByText,
  getAllShapes,
  getCommentAuthor,
  getCommentAuthors,
  getCommentCount,
  getCommentDate,
  getCommentPosition,
  getCommentText,
  getParagraphAlignment,
  getParagraphBullet,
  getParagraphLevel,
  getParagraphSpacing,
  getShapeAnimation,
  getShapeBounds,
  getShapeClickAction,
  getShapeEffect,
  getShapeFill,
  getShapeFlip,
  getShapeHyperlink,
  getShapeId,
  getShapeImageBrightness,
  getShapeImageBytes,
  getShapeImageFillBytes,
  getShapeImageContrast,
  getShapeImageFormat,
  getShapeImageCrop,
  getShapeImageOpacity,
  getShapeKind,
  getShapeName,
  getShapeParagraphCount,
  getShapePlaceholderIdx,
  getMediaParts,
  getPresentationSummary,
  getPresentationTheme,
  getShapePlaceholderType,
  getShapePosition,
  getShapeRotation,
  getShapeRunCount,
  getShapeRunFormat,
  getShapeRunText,
  getShapeSize,
  getShapeStroke,
  getShapeStrokeArrow,
  getShapeStrokeDash,
  getShapeText,
  getShapeTextAnchor,
  getShapeTextAutoFit,
  getShapeTextMargins,
  getShapeTextWrap,
  getShapeZIndex,
  getSlideAt,
  getSlideBackground,
  getSlideCharts,
  getSlideComments,
  getSlideIndex,
  getSlideInfo,
  getSlideLayout,
  getSlideLayoutName,
  getSlideLayoutPlaceholders,
  getSlideLayouts,
  getSlideLayoutType,
  getSlideNotes,
  getSlideSections,
  getSlideShapes,
  getSlideSize,
  getSlideText,
  getSlideTitle,
  getSlideTransition,
  getSlides,
  getSlidesByLayout,
  getTableCell,
  getTableCellAlignment,
  getTableCellFill,
  getTableCellPosition,
  getTableCellText,
  getTableCells,
  getTableColumnWidths,
  getTableDimensions,
  getTableRowHeights,
  importSlide,
  insertTableColumn,
  insertTableRow,
  isSlideHidden,
  listPackageParts,
  loadPresentation,
  moveSlide,
  readPackagePart,
  removeShape,
  removeSlide,
  removeSlideComment,
  removeSlideNotes,
  removeTableColumn,
  removeTableRow,
  renameShape,
  replaceTextInPresentation,
  replaceTextInSlide,
  replaceTokensInPresentation,
  replaceTokensInSlide,
  savePresentation,
  sendShapeBackward,
  sendShapeToBack,
  setChartSpec,
  setMediaPartBytes,
  setShapeAlignment,
  setShapeAnimation,
  setShapeBounds,
  setShapeBullets,
  setShapeFill,
  setShapeFlip,
  setShapeGlow,
  setShapeGradientFill,
  setShapeShadow,
  setShapeHyperlink,
  setShapeImage,
  setShapeImageBrightness,
  setShapeImageContrast,
  setShapeImageCrop,
  setShapeImageFill,
  setShapeImageOpacity,
  setShapeClickAction,
  setShapeNoFill,
  setShapeNoStroke,
  setShapePatternFill,
  setParagraphAlignment,
  setParagraphBullet,
  setParagraphLevel,
  setParagraphSpacing,
  setShapePosition,
  setShapeRotation,
  setShapeRunFormat,
  setShapeRunText,
  setShapeSize,
  setShapeStroke,
  setShapeStrokeArrow,
  setShapeStrokeDash,
  setShapeText,
  setShapeTextAnchor,
  setShapeTextAutoFit,
  setShapeTextFormat,
  setShapeTextMargins,
  setShapeTextWrap,
  setShapeZIndex,
  setSlideBackground,
  setSlideBackgroundImage,
  setSlideHidden,
  setSlideLayout,
  setSlideNotes,
  setSlideSections,
  setSlideSize,
  setSlideTitle,
  setSlideTransition,
  setTableCellAlignment,
  setTableCellFill,
  setTableCellText,
  setTableCellTextFormat,
  sortSlides,
  validatePresentation,
} from './fn.ts';

export type { BulletStyle, ParagraphAlignment, TextFormat } from '../internal/drawingml/index.ts';
export type {
  PresetShape,
  TransitionEffect,
  TransitionOptions,
} from '../internal/presentationml/index.ts';

// Library version. Replaced at build time by the package version.
export const VERSION = '0.0.0';
