// Round-trip integration tests against real PPTX fixtures generated by
// python-pptx. See test/fixtures/minimal/generate.py for the source.

import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { OpcPackage } from '../../src/internal/parts/index.ts';
import { partName } from '../../src/internal/opc/index.ts';
import { Presentation } from '../../src/api/index.ts';
import { expectSemanticallyEqual } from '../lib/semantic-equal.ts';

const fixture = (name: string): string =>
  fileURLToPath(new URL(`./minimal/${name}`, import.meta.url));

const fixtures = ['blank.pptx', 'one-text-slide.pptx', 'two-slides.pptx'] as const;

describe('real-PPTX round-trip (python-pptx fixtures)', () => {
  for (const name of fixtures) {
    it(`${name} loads through the OPC layer`, async () => {
      const bytes = await readFile(fixture(name));
      const pkg = OpcPackage.load(bytes);

      // Every PPTX has [Content_Types].xml resolution working, a root rels
      // pointing at /ppt/presentation.xml, and a presentation.xml part.
      const rootRels = pkg.rootRels();
      expect(rootRels).not.toBeNull();
      const docRel = rootRels?.items.find((r) =>
        r.type.endsWith('/officeDocument'),
      );
      expect(docRel).toBeDefined();
      expect(docRel?.target).toMatch(/presentation\.xml$/);

      const pres = pkg.getPart(partName('/ppt/presentation.xml'));
      expect(pres).not.toBeNull();
      expect(pres?.contentType).toContain('presentationml.presentation.main');
    });

    it(`${name} survives a load → save → re-load round-trip`, async () => {
      const original = await readFile(fixture(name));
      const pkg1 = OpcPackage.load(original);
      const written = pkg1.save();
      const pkg2 = OpcPackage.load(written);
      expectSemanticallyEqual(pkg1, pkg2);
    });

    it(`${name} round-trips through the public Presentation API`, async () => {
      const bytes = await readFile(fixture(name));
      const pres = await Presentation.load(bytes);
      const out = await pres.save();
      // Confirm the second save also loads cleanly through Presentation.
      const again = await Presentation.load(out);
      expect(again).toBeInstanceOf(Presentation);
    });
  }
});
