export const officeStyles = `
.find-replace-dialog{position:fixed;top:155px;right:25px;left:auto;margin:0;z-index:90}.find-replace-dialog label{margin:12px 0}.find-replace-dialog label.search-option{flex-direction:row;align-items:center;gap:7px}.find-replace-dialog [role=status]{min-height:16px}
.presentation-search{display:flex;align-items:center;gap:3px;margin-left:auto;position:relative;z-index:1;background:var(--office-chrome)}
.presentation-search input{width:160px;min-width:80px;font:inherit;padding:2px 5px}
.presentation-search button{padding:0 5px;border:0;background:transparent;font-size:18px}
#find-status{position:absolute;top:100%;right:0;background:var(--office-chrome);white-space:nowrap;font-size:11px;padding:2px 5px;pointer-events:none}
#find-status:empty{display:none}
@media(max-width:900px){.titlebar .document-title{display:none}.presentation-search input{width:130px}}

.application-menubar{display:flex;align-items:center;padding:0 12px;background:var(--office-bg,#f5f5f5);border-bottom:1px solid #d1d1d1;height:26px;box-sizing:border-box;flex:none}
.application-menubar>button{border:0;background:transparent;border-radius:4px;padding:3px 12px;font-size:13px;color:inherit}
.application-menubar>button:hover,.application-menubar>button[aria-expanded=true]{background:var(--office-accent,#b7472a);color:white}
#thumbnails li.has-section{display:flex;flex-direction:column}
.section-heading{order:-1;text-align:left;border:0;background:transparent;font-weight:600;width:100%;margin:4px 0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
#thumbnails [hidden]{display:none!important}
.section-heading.section-selected{background:var(--office-accent);color:white}
.section-disclosure{display:inline-block;width:22px;text-align:center}
.section-heading.section-drop-target{box-shadow:inset 0 3px var(--office-accent)}
.section-heading.section-drop-target.section-drop-after{box-shadow:inset 0 -3px var(--office-accent)}
.section-dialog{color:var(--office-text);background:#303030;border:1px solid #555;border-radius:9px;padding:20px;width:340px;box-shadow:0 15px 50px #0008}
.section-dialog.paragraph-dialog label,.section-dialog.font-dialog label{margin-bottom:10px}.section-dialog.font-dialog .font-effect{flex-direction:row;align-items:center}.paragraph-dialog fieldset,.font-dialog fieldset{border:1px solid #666;padding:12px;margin:12px 0 0}.font-dialog [role=tablist]{display:flex;gap:4px;margin-bottom:16px}.font-dialog [role=tab][aria-selected=true]{background:#666;color:white}.font-dialog [role=tabpanel][hidden]{display:none}.font-dialog input[type=color].mixed-value::-webkit-color-swatch{background:repeating-linear-gradient(135deg,#aaa 0 4px,#eee 4px 8px)!important}.paragraph-dialog select,.font-dialog select{font:inherit;padding:5px}
.section-dialog.columns-dialog label{flex-direction:row;align-items:center;justify-content:space-between;margin:14px 0}.columns-dialog input{width:65px}.action-dialog [role=tablist]{display:flex;justify-content:center;gap:0}.action-dialog [role=tab]{border-radius:0;padding:4px 14px}.action-dialog [role=tab][aria-selected=true]{background:#3578c7;color:white}.action-dialog fieldset{border:1px solid #666;padding:12px;margin:12px 0}.section-dialog.action-dialog fieldset label,.section-dialog.action-dialog .action-sound-label{flex-direction:row;align-items:center;margin:10px 0}.action-dialog select{font:inherit;padding:5px;max-width:100%}.action-dialog footer{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.action-dialog [role=alert]{color:#ffb0a5}.section-dialog::backdrop{background:#0005}.section-dialog h2{font-size:15px;margin:0 0 18px}.section-dialog label{display:flex;flex-direction:column;gap:7px}.section-dialog input{padding:6px;font:inherit}.section-dialog form>div{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}
:root{color-scheme:dark;--office-bg:#262626;--office-chrome:#1f1f1f;--office-border:#414141;--office-text:#e5e5e5;--office-accent:#e98b73}
body{background:var(--office-bg);color:var(--office-text);font:12px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;grid-template-rows:146px minmax(0,1fr) 26px}
button,select,.download{border-color:var(--office-border);border-radius:3px;background:#333;padding:4px 8px}
button:hover:not(:disabled),.download:hover{background:#454545}button:disabled{opacity:.38}
:focus-visible{outline-color:var(--office-accent);outline-offset:1px}
.office-header{position:relative;display:flex;flex-direction:column;align-items:stretch;gap:0;padding:0;background:var(--office-chrome);border-bottom:1px solid #101010}
.titlebar{height:30px;display:flex;align-items:center;gap:12px;padding:0 14px;position:relative;flex:none}
.app-mark{background:#b7472a;color:white;font-size:13px;font-weight:700;width:19px;height:21px;display:grid;place-items:center;border-radius:2px}
.quick-save{display:flex;color:#bbb}.quick-save svg{width:17px;height:17px}
.document-title{position:absolute;left:50%;transform:translateX(-50%);font-size:12px;white-space:nowrap}.document-title span{color:#aaa}#status{flex:none;margin-left:0;color:#aaa;font-size:10px;max-width:30%;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}
.tabbar{display:flex;align-items:center;height:26px;gap:8px;padding:0 10px;flex:none}.tabbar [role=tablist]{display:flex;align-self:stretch;gap:20px;margin-right:auto}.tabbar [role=tab]{border:0;border-radius:0;background:none;padding:0 0 4px;color:#bbb;position:relative;font-size:12px}.tabbar [role=tab][aria-selected=true]{color:#fff;font-weight:600}.tabbar [role=tab][aria-selected=true]::after{content:"";height:3px;border-radius:2px;background:var(--office-accent);position:absolute;bottom:0;left:0;right:0}
#toggle-chat{display:flex;align-items:center;gap:5px;height:23px;background:#383838;border-color:#555;color:#eee;font-size:11px}#toggle-chat svg{width:15px;height:15px}#toggle-chat[aria-expanded=true]{background:#494949;border-color:#777;color:white}.tabbar .download{font-size:11px;padding:3px 9px;background:#a63c24;color:#fff;border-color:#a63c24}
.ribbon{display:flex;align-items:stretch;gap:0;height:63px;padding:4px 8px 3px;overflow-x:auto;flex:none}.ribbon-group{position:relative;display:flex;align-items:flex-start;gap:3px;border-right:1px solid #494949;padding:0 9px;flex:none}.group-label{display:none;position:absolute;bottom:0;left:0;right:0;text-align:center;color:#aaa;font-size:9px}.ribbon-command{display:flex;align-items:center;justify-content:flex-start;flex-direction:column;gap:3px;min-width:50px;height:55px;background:transparent;border:1px solid transparent;padding:2px 5px;font-size:10px;line-height:12px}#present{background:transparent;border-color:transparent;box-shadow:none;color:inherit}#present:hover:not(:disabled){background:#454545}.ribbon-command svg{width:25px;height:25px;color:#90b5cf}.ribbon-command[aria-pressed=true]{background:#424242;border-color:#666}.ribbon-stack{display:flex;flex-direction:column;gap:3px}.ribbon-stack button{display:flex;gap:5px;align-items:center;border:0;background:none;font-size:11px;text-align:left;padding:3px}.ribbon-stack svg{width:16px;height:16px}.ribbon-check{display:flex;align-items:center;gap:5px;margin:8px 5px;font-size:11px}.ribbon-check input{accent-color:var(--office-accent)}
#collapse-ribbon{position:absolute;bottom:2px;right:5px;background:var(--office-chrome);border:0;padding:0 6px;height:16px;color:#aaa}.ribbon-collapsed{grid-template-rows:83px minmax(0,1fr) 26px}.ribbon-collapsed .ribbon{display:none}.ribbon-collapsed #collapse-ribbon{bottom:0;right:0;transform:rotate(180deg)}
.workspace{--filmstrip-width:212px;--chat-width:320px;background:var(--office-bg)}
.filmstrip{background:#262626;border-color:#101010;padding:8px 15px 12px 5px;scrollbar-color:#777 #262626;scrollbar-width:thin}#thumbnails{gap:8px}.thumbnail{padding:3px 2px;gap:8px;border-radius:0}.thumbnail img{width:calc(100% - 26px);border:2px solid transparent;border-radius:2px;box-shadow:0 0 2px #0008}.slide-number{color:#e5e5e5;font-size:11px;padding-top:0}.thumbnail[aria-current=true]{background:transparent;box-shadow:none}.thumbnail[aria-current=true] img{border-color:var(--office-accent);box-shadow:0 0 0 1px var(--office-accent)}.thumbnail[aria-current=true] .slide-number{color:#fff;font-weight:400}.thumbnail:hover:not(:disabled){background:#333}
#stage{background:#292929;padding:20px 28px;scrollbar-color:#777 #292929}#slide{box-shadow:0 1px 7px #0005}#empty{color:#bbb}
#chat{background:#252525;border-left:1px solid #101010}.workspace-heading{padding:9px 12px;height:38px;letter-spacing:0;font-size:14px;font-weight:500;color:#eee;border-bottom:1px solid #414141}.workspace-heading button{font-size:20px;padding:0 4px;border:0;background:none;line-height:20px}.agent-pane{padding:0 5px 5px}.agent-tools{background:#292929;border-color:#444;border-radius:0;padding:4px}.agent-tools span{color:#ccc;letter-spacing:0}.agent-pane:focus-within .agent-tools{border-color:#666;background:#333}.agent-pane iframe{border-radius:0}.agent-divider{background:#333}.agent-divider:hover,.agent-divider:focus-visible{background:var(--office-accent)}#chat-resizer:hover::after,#chat-resizer:focus-visible::after,.resizing-chat #chat-resizer::after{background:var(--office-accent)}
footer{gap:8px;padding:0 10px;background:#262626;border-color:#454545;font-size:10px;color:#ddd}#count{font-size:10px;font-weight:400}.footer-spacer{flex:1}footer button{border:0;background:none;border-radius:0;padding:3px 5px;font-size:10px;height:24px;display:flex;align-items:center;gap:4px}footer svg{width:16px;height:16px}footer button[aria-pressed=true]{background:#515151}.zoom-controls{display:flex;align-items:center;gap:2px}#zoom-slider{width:98px;height:16px;accent-color:#ccc;cursor:pointer}#zoom-level{min-width:42px;justify-content:center}#zoom-out,#zoom-in{font-size:16px;width:22px;justify-content:center}
#grid-dialog{width:390px;padding:0;border:1px solid #666;border-radius:18px;background:#202020;color:#eee;box-shadow:0 15px 60px #0008;font-size:13px}#grid-dialog::backdrop{background:#0007}#grid-dialog h2{font-size:13px;text-align:center;border-bottom:1px solid #444;margin:0;padding:10px}#grid-dialog fieldset{border:0;border-radius:12px;background:#282828;margin:24px 20px;padding:16px 20px;display:flex;flex-direction:column;gap:8px}#grid-dialog legend{font-weight:600;padding:0 0 8px}#grid-dialog label{display:flex;align-items:center;gap:6px}#grid-dialog label[hidden]{display:none}#grid-dialog input[type=checkbox]{width:16px;height:16px;margin:0;accent-color:#777}#grid-dialog select,#grid-dialog input[type=number]{background:#444;color:#eee;border:0;border-radius:5px;font:inherit;padding:3px 6px}#grid-dialog input[type=number]{width:60px}#grid-dialog #grid-default{margin-right:auto}#grid-dialog .dialog-actions button{min-width:42px;background:#3d3d3d;color:#eee}
#zoom-dialog{width:194px;border:1px solid #666;border-radius:7px;background:#303030;color:#eee;padding:0;box-shadow:0 15px 60px #0008;font-size:13px}#zoom-dialog::backdrop{background:transparent}#zoom-dialog h2{font-size:13px;font-weight:600;text-align:center;margin:0 0 12px;padding:6px;background:#3a3a3a;border-bottom:1px solid #242424}.zoom-presets{display:flex;flex-direction:column;gap:7px;border:0;margin:0;padding:0 19px}.zoom-presets label{display:flex;align-items:center;gap:6px;height:16px}.zoom-presets input{margin:0;width:14px;height:14px;accent-color:#1685f8}.zoom-custom{display:flex;align-items:center;justify-content:space-between;margin:14px 19px}.zoom-custom input{width:70px;padding:2px 4px;border:1px solid #777;border-radius:4px;background:#252525;color:#eee;font:inherit}.dialog-actions{display:flex;justify-content:flex-end;gap:10px;padding:0 17px 16px}.dialog-actions button{min-width:70px;padding:3px 8px;border:0;border-radius:5px;background:#626262;font-size:12px}.dialog-actions button[value=apply]{background:#087bfa;color:white}
.office-menu{position:fixed;z-index:100;min-width:180px;max-height:calc(100dvh - 8px);overflow:auto;padding:5px;background:#303030f5;border:1px solid #626262;border-radius:6px;box-shadow:0 6px 24px #0007;font-size:13px}.office-menu button{display:flex;justify-content:space-between;gap:24px;width:100%;padding:3px 14px;border:0;border-radius:3px;text-align:left;background:transparent;font:inherit}.office-menu button:focus,.office-menu button:hover:not(:disabled){outline:none;background:#176bce;color:white}.office-menu.layout-gallery{display:grid;grid-template-columns:repeat(3,96px);gap:3px;min-width:0;padding:7px}.office-menu.layout-gallery[hidden]{display:none}.office-menu.layout-gallery button{width:96px;padding:5px;gap:4px;flex-direction:column;align-items:center;font-size:10px;text-align:center;justify-content:start}.layout-gallery button[aria-checked=true]{outline:1px solid #aaa;outline-offset:-2px}.layout-gallery svg{width:86px;height:50px;background:white;fill:none;stroke:#777;stroke-width:1;stroke-dasharray:3 2}.layout-gallery span{max-width:100%}
.office-menu.shape-gallery{display:grid;grid-template-columns:repeat(10,30px);gap:2px;width:330px;min-width:0;padding:8px;max-height:min(650px,calc(100dvh - 16px))}.office-menu.shape-gallery[hidden]{display:none}.shape-gallery .gallery-heading{grid-column:1/-1;padding:7px 4px 3px;font-size:12px;color:#d5d5d5}.office-menu.shape-gallery button{width:30px;height:30px;padding:3px;gap:0;justify-content:center;align-items:center}.shape-gallery svg{width:24px;height:24px;fill:none;stroke:currentColor;stroke-width:1;stroke-linejoin:round}.office-menu.shape-gallery button:focus{outline:1px solid #a8cfff;outline-offset:-1px}
.office-menu [role=separator]{height:1px;background:#595959;margin:5px 8px}.office-menu button:disabled{opacity:.35}
main{position:relative}#filmstrip-resizer{position:absolute;left:-4px;top:0;bottom:0;width:8px;cursor:col-resize;touch-action:none;z-index:4}#filmstrip-resizer:hover,#filmstrip-resizer:focus-visible{background:#7775}.resizing-filmstrip,.resizing-filmstrip *{cursor:col-resize!important;user-select:none!important}.resizing-filmstrip iframe{pointer-events:none}.thumbnails-hidden #filmstrip-resizer,.presenting #filmstrip-resizer{display:none}
#show-screen{position:fixed;inset:0;background:black;z-index:10;color:white;text-align:center;font-size:16px;padding:20px;cursor:default}#show-screen.white{background:white}.presenting #stage{background:#000}.presenting #presentation-controls{z-index:11;left:12px;bottom:10px;transform:none;border-radius:0;background:#262626bf;padding:2px;gap:3px}.presenting #presentation-controls button{border:0;font-size:12px}.presenting #present-count{font-size:11px;padding:0 6px}
body.chat-hidden .workspace{grid-template-columns:var(--filmstrip-width) minmax(0,1fr)}body.thumbnails-hidden .workspace{--filmstrip-width:0px!important}body.thumbnails-hidden .filmstrip{display:none}
body.presenting{grid-template-rows:minmax(0,1fr)}.presenting .office-header{display:none}body.presenting .workspace{grid-template-columns:minmax(0,1fr)}.presenting #stage{padding:0;background:#000}
@media(max-width:1000px){.workspace{--filmstrip-width:160px;--chat-width:300px}#stage{padding:16px}}
@media(max-width:700px){#filmstrip-resizer{display:none}body{grid-template-rows:146px minmax(0,1fr) 26px}.document-title{position:static;transform:none;margin-right:auto}.document-title span{display:none}#status{max-width:35%;font-size:9px}.titlebar{padding:0 10px;gap:8px}.tabbar [role=tablist]{gap:14px}.tabbar .download{font-size:10px}.workspace{grid-template-columns:minmax(0,1fr);grid-template-rows:minmax(160px,1fr) minmax(200px,1fr)}body.chat-hidden .workspace{grid-template-columns:minmax(0,1fr);grid-template-rows:minmax(0,1fr)}.filmstrip{display:none}#status-agents{display:none}#zoom-slider{width:60px}.ribbon-collapsed{grid-template-rows:83px minmax(0,1fr) 26px}body.presenting{grid-template-rows:minmax(0,1fr)}body.presenting .workspace{grid-template-rows:minmax(0,1fr)}}

.show-properties-dialog{width:580px;max-width:calc(100vw - 40px)}
.show-properties-dialog fieldset{border:1px solid #ccc;border-radius:5px;padding:12px;margin:12px 0}
.show-properties-dialog fieldset>label{display:block;margin:8px 0}
.section-dialog.show-properties-dialog form>.show-settings-columns{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:0}
.section-dialog.show-properties-dialog label{flex-direction:row;align-items:center;gap:5px}
.show-properties-dialog fieldset{min-width:0}
.show-properties-dialog .show-range{display:flex;align-items:center;gap:5px;margin:8px 0}
.show-properties-dialog .show-range label{white-space:nowrap}
.show-properties-dialog footer{display:flex;justify-content:flex-end;gap:8px;background:none;border:0;padding:0;margin-top:18px}
.show-properties-dialog footer button{font:inherit;min-width:70px;background:#626262;border-radius:5px;justify-content:center}
.show-properties-dialog footer button[type=submit]{background:#087bfa;color:white}
.show-properties-dialog input[type=number]{width:44px;padding:4px}
.show-properties-dialog select{width:100%}
body.kiosk-show #presentation-controls{display:none}
#ribbon-animations .ribbon-stack{gap:0;font-size:11px;line-height:18px}#ribbon-animations .ribbon-stack label{display:flex;align-items:center;justify-content:space-between;gap:5px;height:18px}#animation-start,#animation-duration,#animation-delay{box-sizing:border-box;height:18px;padding:0 4px;font-size:11px}
#ribbon-transitions .ribbon-stack{gap:0;font-size:11px;line-height:14px}#ribbon-transitions .ribbon-check{margin:0;height:20px}#advance-time{height:19px;padding:0 4px;font-size:11px}

#browse-scrollbar{position:fixed;right:0;top:0;bottom:0;width:16px;overflow-y:scroll;overflow-x:hidden;z-index:12;background:#eee;scrollbar-width:thin}#browse-scrollbar[hidden]{display:none}#browse-scrollbar>div{width:1px;pointer-events:none}.presenting.browse-scrollbar-visible #stage{margin-right:16px}.show-properties-dialog .show-scrollbar-option{margin-left:24px}

.transition-gallery{display:flex;align-items:center;gap:2px}.transition-tile{display:flex;flex-direction:column;align-items:center;justify-content:center;width:62px;height:51px;padding:0;border:1px solid transparent;border-radius:2px;background:transparent;font-size:10px;color:inherit}.transition-tile svg{width:43px;height:32px;color:#6a9db9}.transition-tile[aria-pressed=true]{border-color:#c76b4e;background:#624138}.transition-tile:hover{background:#454545}
#show-laser-pointer{position:fixed;z-index:10000;width:12px;height:12px;border-radius:50%;pointer-events:none;transform:translate(-50%,-50%);background:radial-gradient(circle,#fff 0%,#ffb3b3 18%,#ff1919 42%,#d40000 65%,transparent 75%);box-shadow:0 0 6px 2px #f33}
#show-laser-pointer[data-color="green"]{background:radial-gradient(circle,#fff 0%,#b3ffb3 18%,#19ff19 42%,#00a400 65%,transparent 75%);box-shadow:0 0 6px 2px #3f3}
#show-laser-pointer[data-color="blue"]{background:radial-gradient(circle,#fff 0%,#b3b3ff 18%,#1919ff 42%,#0000d4 65%,transparent 75%);box-shadow:0 0 6px 2px #33f}
`;
