"""Generate preset connection definitions from the checked-in ECMA-376 geometry reference."""
from pathlib import Path
import json
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
ns = 'http://schemas.openxmlformats.org/drawingml/2006/main'
ET.register_namespace('a', ns)
source = root / 'references/ecma-376-5th/ECMA-376/OfficeOpenXML-DrawingMLGeometries/presetShapeDefinitions.xml'
definitions = {}
for shape in ET.parse(source).getroot():
    sites = shape.find(f'{{{ns}}}cxnLst')
    if sites is None or not len(sites):
        continue
    geometry = ET.Element(f'{{{ns}}}custGeom')
    for name in ['avLst', 'gdLst', 'cxnLst']:
        child = shape.find(f'{{{ns}}}{name}')
        if child is not None:
            geometry.append(child)
    for node in geometry.iter():
        node.text = None
        node.tail = None
    definitions[shape.tag] = ET.tostring(geometry, encoding='unicode')
output = root / 'src/internal/drawingml/preset-connection-sites.ts'
output.write_text('// Generated by tools/generate-connection-sites.py from ECMA-376 presetShapeDefinitions.xml.\n'
                  'export const presetConnectionSites: Readonly<Record<string, string>> = ' + json.dumps(definitions, indent=2) + ';\n')
